# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Api.Slurm do
  @moduledoc """
  API calls for all endpoints tagged `Slurm`.
  """

  alias SlurmRestAPI.Connection
  import SlurmRestAPI.RequestBuilder

  @doc """
  cancel or signal job

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `job_id` (String.t): Slurm Job ID
  - `opts` (keyword): Optional parameters
    - `:signal` (String.t): signal to send to job

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_cancel_job(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_cancel_job(connection, job_id, opts \\ []) do
    optional_params = %{
      :signal => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/slurm/v0.0.39/job/#{job_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  delete node

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `node_name` (String.t): Slurm Node Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_delete_node(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_delete_node(connection, node_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurm/v0.0.39/node/#{node_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get diagnostics

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039Diag.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_diag(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.V0039Diag.t} | {:error, Tesla.Env.t}
  def slurm_v0039_diag(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/diag")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039Diag{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get job info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `job_id` (String.t): Slurm JobID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039JobsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_get_job(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SlurmRestAPI.Model.V0039JobsResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0039_get_job(connection, job_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/job/#{job_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039JobsResponse{}},
      {:default, false}
    ])
  end

  @doc """
  get list of jobs

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if changed since update_time. Use of this parameter can result in faster replies.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039JobsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_get_jobs(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.V0039JobsResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0039_get_jobs(connection, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/jobs")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039JobsResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get node info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `node_name` (String.t): Slurm Node Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039NodesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_get_node(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.V0039NodesResponse.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_get_node(connection, node_name, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/node/#{node_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039NodesResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get all node info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if changed since update_time. Use of this parameter can result in faster replies.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039NodesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_get_nodes(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.V0039NodesResponse.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_get_nodes(connection, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/nodes")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039NodesResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get partition info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `partition_name` (String.t): Slurm Partition Name
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if there were no partition changes (not limited to partition in URL endpoint) since update_time.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039PartitionsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_get_partition(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.V0039PartitionsResponse.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_get_partition(connection, partition_name, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/partition/#{partition_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039PartitionsResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get all partition info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if changed since update_time. Use of this parameter can result in faster replies.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039PartitionsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_get_partitions(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.V0039PartitionsResponse.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_get_partitions(connection, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/partitions")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039PartitionsResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get reservation info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `reservation_name` (String.t): Slurm Reservation Name
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if no reservation (not limited to reservation in URL) changed since update_time.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039ReservationsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_get_reservation(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.V0039ReservationsResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0039_get_reservation(connection, reservation_name, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/reservation/#{reservation_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039ReservationsResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get all reservation info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if changed since update_time. Use of this parameter can result in faster replies.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039ReservationsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_get_reservations(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.V0039ReservationsResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0039_get_reservations(connection, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/reservations")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039ReservationsResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  ping test

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039Pings.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_ping(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.V0039Pings.t} | {:error, Tesla.Env.t}
  def slurm_v0039_ping(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/ping")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039Pings{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  get all Slurm tracked license info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039LicensesInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_slurmctld_get_licenses(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, SlurmRestAPI.Model.V0039LicensesInfo.t} | {:error, Tesla.Env.t}
  def slurm_v0039_slurmctld_get_licenses(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.39/licenses")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039LicensesInfo{}},
      {:default, false}
    ])
  end

  @doc """
  submit new job

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `v0039_job_submission` (V0039JobSubmission): submit new job
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039JobSubmissionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_submit_job(Tesla.Env.client, SlurmRestAPI.Model.V0039JobSubmission.t, keyword()) :: {:ok, SlurmRestAPI.Model.V0039JobSubmissionResponse.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_submit_job(connection, v0039_job_submission, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurm/v0.0.39/job/submit")
      |> add_param(:body, :body, v0039_job_submission)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039JobSubmissionResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  update job

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `job_id` (String.t): Slurm Job ID
  - `v0039_job_desc_msg` (V0039JobDescMsg): update job
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0039JobUpdateResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_update_job(Tesla.Env.client, String.t, SlurmRestAPI.Model.V0039JobDescMsg.t, keyword()) :: {:ok, SlurmRestAPI.Model.V0039JobUpdateResponse.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_update_job(connection, job_id, v0039_job_desc_msg, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurm/v0.0.39/job/#{job_id}")
      |> add_param(:body, :body, v0039_job_desc_msg)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0039JobUpdateResponse{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  update node properties

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `node_name` (String.t): Slurm Node Name
  - `v0039_update_node_msg` (V0039UpdateNodeMsg): update node
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0039_update_node(Tesla.Env.client, String.t, SlurmRestAPI.Model.V0039UpdateNodeMsg.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurm_v0039_update_node(connection, node_name, v0039_update_node_msg, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurm/v0.0.39/node/#{node_name}")
      |> add_param(:body, :body, v0039_update_node_msg)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Add clusters

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0039_clusters_info` (Dbv0039ClustersInfo): Add or update clusters
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_add_clusters(Tesla.Env.client, SlurmRestAPI.Model.Dbv0039ClustersInfo.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_add_clusters(connection, dbv0039_clusters_info, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.39/clusters")
      |> add_param(:body, :body, dbv0039_clusters_info)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Add wckeys

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (Dbv0039WckeyInfo): add wckeys

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_add_wckeys(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_add_wckeys(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.39/wckeys")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Delete account

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `account_name` (String.t): Slurm Account Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_delete_account(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_delete_account(connection, account_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.39/account/#{account_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Delete association

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:cluster` (String.t): Cluster name
    - `:account` (String.t): Account name
    - `:user` (String.t): User name
    - `:partition` (String.t): Partition Name

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039ResponseAssociationsDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_delete_association(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.Dbv0039ResponseAssociationsDelete.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_delete_association(connection, opts \\ []) do
    optional_params = %{
      :cluster => :query,
      :account => :query,
      :user => :query,
      :partition => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.39/association")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039ResponseAssociationsDelete{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Delete associations

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:cluster` (String.t): Cluster name
    - `:account` (String.t): Account name
    - `:user` (String.t): User name
    - `:partition` (String.t): Partition Name

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039ResponseAssociationsDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_delete_associations(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.Dbv0039ResponseAssociationsDelete.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_delete_associations(connection, opts \\ []) do
    optional_params = %{
      :cluster => :query,
      :account => :query,
      :user => :query,
      :partition => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.39/associations")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039ResponseAssociationsDelete{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Delete cluster

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `cluster_name` (String.t): Slurm cluster name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_delete_cluster(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_delete_cluster(connection, cluster_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.39/cluster/#{cluster_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Delete QOS

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `qos_name` (String.t): Slurm QOS Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_delete_qos(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_delete_qos(connection, qos_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.39/qos/#{qos_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Delete user

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `user_name` (String.t): Slurm User Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_delete_user(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_delete_user(connection, user_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.39/user/#{user_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Delete wckey

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `wckey` (String.t): Slurm wckey name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_delete_wckey(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_delete_wckey(connection, wckey, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.39/wckey/#{wckey}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get slurmdb diagnostics

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039Diag.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_diag(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039Diag.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_diag(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/diag")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039Diag{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get account info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `account_name` (String.t): Slurm Account Name
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (String.t): Include deleted accounts. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039AccountInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_account(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.Dbv0039AccountInfo.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_account(connection, account_name, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/account/#{account_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039AccountInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get account list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (String.t): Include deleted accounts. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039AccountInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_accounts(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.Dbv0039AccountInfo.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_accounts(connection, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/accounts")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039AccountInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get association info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:cluster` (String.t): Cluster name
    - `:account` (String.t): Account name
    - `:user` (String.t): User name
    - `:partition` (String.t): Partition Name

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039AssociationsInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_association(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039AssociationsInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_association(connection, opts \\ []) do
    optional_params = %{
      :cluster => :query,
      :account => :query,
      :user => :query,
      :partition => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/association")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039AssociationsInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get association list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:cluster` (String.t): Cluster name
    - `:account` (String.t): Account name
    - `:user` (String.t): User name
    - `:partition` (String.t): Partition Name

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039AssociationsInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_associations(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039AssociationsInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_associations(connection, opts \\ []) do
    optional_params = %{
      :cluster => :query,
      :account => :query,
      :user => :query,
      :partition => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/associations")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039AssociationsInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get cluster info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `cluster_name` (String.t): Slurm cluster name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039ClustersInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_cluster(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.Dbv0039ClustersInfo.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_cluster(connection, cluster_name, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/cluster/#{cluster_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039ClustersInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get cluster list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039ClustersInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_clusters(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:ok, SlurmRestAPI.Model.Dbv0039ClustersInfo.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_clusters(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/clusters")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039ClustersInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Dump all configuration information

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039ConfigInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_config(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039ConfigInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_config(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/config")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039ConfigInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get job info
  This endpoint may return multiple job entries since job_id is not a unique key - only the tuple (cluster, job_id, start_time) is unique. If the requested job_id is a component of a heterogeneous job all components are returned.

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `job_id` (String.t): Slurm JobID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039JobInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_job(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039JobInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_job(connection, job_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/job/#{job_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039JobInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get job list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:users` (String.t): Filter by comma delimited list of user names
    - `:submit_time` (String.t): Filter by submission time  Accepted formats:  HH:MM[:SS] [AM|PM]  MMDD[YY] or MM/DD[/YY] or MM.DD[.YY]  MM/DD[/YY]-HH:MM[:SS]  YYYY-MM-DD[THH:MM[:SS]]
    - `:start_time` (String.t): Filter by start time  Accepted formats:  HH:MM[:SS] [AM|PM]  MMDD[YY] or MM/DD[/YY] or MM.DD[.YY]  MM/DD[/YY]-HH:MM[:SS]  YYYY-MM-DD[THH:MM[:SS]]
    - `:end_time` (String.t): Filter by end time  Accepted formats:  HH:MM[:SS] [AM|PM]  MMDD[YY] or MM/DD[/YY] or MM.DD[.YY]  MM/DD[/YY]-HH:MM[:SS]  YYYY-MM-DD[THH:MM[:SS]]
    - `:account` (String.t): Comma delimited list of accounts to match
    - `:association` (String.t): Comma delimited list of associations to match
    - `:cluster` (String.t): Comma delimited list of cluster to match
    - `:constraints` (String.t): Comma delimited list of constraints to match
    - `:cpus_max` (String.t): Number of CPUs high range
    - `:cpus_min` (String.t): Number of CPUs low range
    - `:skip_steps` (String.t): Report job step information
    - `:disable_wait_for_result` (String.t): Disable waiting for result from slurmdbd
    - `:exit_code` (String.t): Exit code of job
    - `:format` (String.t): Comma delimited list of formats to match
    - `:group` (String.t): Comma delimited list of groups to match
    - `:job_name` (String.t): Comma delimited list of job names to match
    - `:nodes_max` (String.t): Number of nodes high range
    - `:nodes_min` (String.t): Number of nodes low range
    - `:partition` (String.t): Comma delimited list of partitions to match
    - `:qos` (String.t): Comma delimited list of QOS to match
    - `:reason` (String.t): Comma delimited list of job reasons to match
    - `:reservation` (String.t): Comma delimited list of reservations to match
    - `:state` (String.t): Comma delimited list of states to match
    - `:step` (String.t): Comma delimited list of job steps to match
    - `:node` (String.t): Comma delimited list of used nodes to match
    - `:wckey` (String.t): Comma delimited list of wckeys to match

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039JobInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_jobs(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039JobInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_jobs(connection, opts \\ []) do
    optional_params = %{
      :users => :query,
      :submit_time => :query,
      :start_time => :query,
      :end_time => :query,
      :account => :query,
      :association => :query,
      :cluster => :query,
      :constraints => :query,
      :cpus_max => :query,
      :cpus_min => :query,
      :skip_steps => :query,
      :disable_wait_for_result => :query,
      :exit_code => :query,
      :format => :query,
      :group => :query,
      :job_name => :query,
      :nodes_max => :query,
      :nodes_min => :query,
      :partition => :query,
      :qos => :query,
      :reason => :query,
      :reservation => :query,
      :state => :query,
      :step => :query,
      :node => :query,
      :wckey => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/jobs")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039JobInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get QOS list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (String.t): Include deleted QOSs. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039QosInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_qos(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039QosInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_qos(connection, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/qos")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039QosInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get QOS info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `qos_name` (String.t): Slurm QOS Name
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (String.t): Include deleted QOSs. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039QosInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_single_qos(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039QosInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_single_qos(connection, qos_name, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/qos/#{qos_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039QosInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get TRES info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039TresInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_tres(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, SlurmRestAPI.Model.Dbv0039TresInfo.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_tres(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/tres")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039TresInfo{}},
      {:default, false}
    ])
  end

  @doc """
  Get user info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `user_name` (String.t): Slurm User Name
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (String.t): Include deleted users. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039UserInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_user(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039UserInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_user(connection, user_name, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/user/#{user_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039UserInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get user list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (String.t): Include deleted users. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039UserInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_users(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039UserInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_users(connection, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/users")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039UserInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get wckey info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `wckey` (String.t): Slurm wckey name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039WckeyInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_wckey(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039WckeyInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_wckey(connection, wckey, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/wckey/#{wckey}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039WckeyInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Get wckey list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0039WckeyInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_get_wckeys(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0039WckeyInfo.t} | {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_get_wckeys(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.39/wckeys")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0039WckeyInfo{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Load all configuration information

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (Dbv0039SetConfig): Add or update config

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_set_config(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_set_config(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.39/config")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Update accounts

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0039_account_info` (Dbv0039AccountInfo): update/create accounts
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_update_accounts(Tesla.Env.client, SlurmRestAPI.Model.Dbv0039AccountInfo.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_update_accounts(connection, dbv0039_account_info, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.39/accounts")
      |> add_param(:body, :body, dbv0039_account_info)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Set associations info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0039_associations_info` (Dbv0039AssociationsInfo): Add or update associations
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_update_associations(Tesla.Env.client, SlurmRestAPI.Model.Dbv0039AssociationsInfo.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_update_associations(connection, dbv0039_associations_info, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.39/associations")
      |> add_param(:body, :body, dbv0039_associations_info)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Set QOS info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0039_update_qos` (Dbv0039UpdateQos): Add or update QOSs
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_update_qos(Tesla.Env.client, SlurmRestAPI.Model.Dbv0039UpdateQos.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_update_qos(connection, dbv0039_update_qos, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.39/qos")
      |> add_param(:body, :body, dbv0039_update_qos)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Set TRES info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0039_tres_update` (Dbv0039TresUpdate): Add or Update TRES
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_update_tres(Tesla.Env.client, SlurmRestAPI.Model.Dbv0039TresUpdate.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_update_tres(connection, dbv0039_tres_update, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.39/tres")
      |> add_param(:body, :body, dbv0039_tres_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end

  @doc """
  Update user

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0039_update_users` (Dbv0039UpdateUsers): add or update user
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Status.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0039_update_users(Tesla.Env.client, SlurmRestAPI.Model.Dbv0039UpdateUsers.t, keyword()) :: {:ok, SlurmRestAPI.Model.Status.t} | {:error, Tesla.Env.t}
  def slurmdb_v0039_update_users(connection, dbv0039_update_users, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.39/users")
      |> add_param(:body, :body, dbv0039_update_users)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Status{}},
      {:default, %SlurmRestAPI.Model.Status{}}
    ])
  end
end
