# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Api.Slurm do
  @moduledoc """
  API calls for all endpoints tagged `Slurm`.
  """

  alias SlurmRestAPI.Connection
  import SlurmRestAPI.RequestBuilder

  @doc """
  cancel or signal job

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `job_id` (String.t): Slurm Job ID
  - `opts` (keyword): Optional parameters
    - `:signal` (V0038Signal): signal to send to job

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_cancel_job(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def slurm_v0038_cancel_job(connection, job_id, opts \\ []) do
    optional_params = %{
      :signal => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/slurm/v0.0.38/job/#{job_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {500, false}
    ])
  end

  @doc """
  get diagnostics

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038Diag.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_diag(Tesla.Env.client, keyword()) :: {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:ok, SlurmRestAPI.Model.V0038Diag.t} | {:error, Tesla.Env.t}
  def slurm_v0038_diag(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/diag")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038Diag{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  get job info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `job_id` (String.t): Slurm JobID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038JobsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_get_job(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, SlurmRestAPI.Model.V0038JobsResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0038_get_job(connection, job_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/job/#{job_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038JobsResponse{}},
      {:default, false}
    ])
  end

  @doc """
  get list of jobs

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if changed since update_time. Use of this parameter can result in faster replies.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038JobsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_get_jobs(Tesla.Env.client, keyword()) :: {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:ok, SlurmRestAPI.Model.V0038JobsResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0038_get_jobs(connection, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/jobs")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038JobsResponse{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  get node info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `node_name` (String.t): Slurm Node Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038NodesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_get_node(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.V0038NodesResponse.t} | {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:error, Tesla.Env.t}
  def slurm_v0038_get_node(connection, node_name, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/node/#{node_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038NodesResponse{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  get all node info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if changed since update_time. Use of this parameter can result in faster replies.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038NodesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_get_nodes(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.V0038NodesResponse.t} | {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:error, Tesla.Env.t}
  def slurm_v0038_get_nodes(connection, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/nodes")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038NodesResponse{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  get partition info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `partition_name` (String.t): Slurm Partition Name
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if there were no partition changes (not limited to partition in URL endpoint) since update_time.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038PartitionsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_get_partition(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.V0038PartitionsResponse.t} | {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:error, Tesla.Env.t}
  def slurm_v0038_get_partition(connection, partition_name, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/partition/#{partition_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038PartitionsResponse{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  get all partition info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if changed since update_time. Use of this parameter can result in faster replies.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038PartitionsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_get_partitions(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.V0038PartitionsResponse.t} | {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:error, Tesla.Env.t}
  def slurm_v0038_get_partitions(connection, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/partitions")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038PartitionsResponse{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  get reservation info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `reservation_name` (String.t): Slurm Reservation Name
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if no reservation (not limited to reservation in URL) changed since update_time.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038ReservationsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_get_reservation(Tesla.Env.client, String.t, keyword()) :: {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:ok, SlurmRestAPI.Model.V0038ReservationsResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0038_get_reservation(connection, reservation_name, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/reservation/#{reservation_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038ReservationsResponse{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  get all reservation info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:update_time` (integer()): Filter if changed since update_time. Use of this parameter can result in faster replies.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038ReservationsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_get_reservations(Tesla.Env.client, keyword()) :: {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:ok, SlurmRestAPI.Model.V0038ReservationsResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0038_get_reservations(connection, opts \\ []) do
    optional_params = %{
      :update_time => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/reservations")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038ReservationsResponse{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  ping test

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038Pings.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_ping(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.V0038Pings.t} | {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:error, Tesla.Env.t}
  def slurm_v0038_ping(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/ping")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038Pings{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  get all Slurm tracked license info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038Licenses.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_slurmctld_get_licenses(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, SlurmRestAPI.Model.V0038Licenses.t} | {:error, Tesla.Env.t}
  def slurm_v0038_slurmctld_get_licenses(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurm/v0.0.38/licenses")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038Licenses{}},
      {:default, false}
    ])
  end

  @doc """
  submit new job

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `v0038_job_submission` (V0038JobSubmission): submit new job
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.V0038JobSubmissionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_submit_job(Tesla.Env.client, SlurmRestAPI.Model.V0038JobSubmission.t, keyword()) :: {:ok, list(SlurmRestAPI.Model.V0038Error.t)} | {:ok, SlurmRestAPI.Model.V0038JobSubmissionResponse.t} | {:error, Tesla.Env.t}
  def slurm_v0038_submit_job(connection, v0038_job_submission, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurm/v0.0.38/job/submit")
      |> add_param(:body, :body, v0038_job_submission)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.V0038JobSubmissionResponse{}},
      {:default, [%SlurmRestAPI.Model.V0038Error{}]}
    ])
  end

  @doc """
  update job

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `job_id` (String.t): Slurm Job ID
  - `v0038_job_properties` (V0038JobProperties): update job
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurm_v0038_update_job(Tesla.Env.client, String.t, SlurmRestAPI.Model.V0038JobProperties.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def slurm_v0038_update_job(connection, job_id, v0038_job_properties, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurm/v0.0.38/job/#{job_id}")
      |> add_param(:body, :body, v0038_job_properties)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {500, false}
    ])
  end

  @doc """
  Add clusters

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0038_clusters_properties` (Dbv0038ClustersProperties): Add or update clusters
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseClusterAdd.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_add_clusters(Tesla.Env.client, SlurmRestAPI.Model.Dbv0038ClustersProperties.t, keyword()) :: {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:ok, SlurmRestAPI.Model.Dbv0038ResponseClusterAdd.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_add_clusters(connection, dbv0038_clusters_properties, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.38/clusters")
      |> add_param(:body, :body, dbv0038_clusters_properties)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseClusterAdd{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Add wckeys

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (Dbv0038WckeyInfo): add wckeys

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseWckeyAdd.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_add_wckeys(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ResponseWckeyAdd.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_add_wckeys(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.38/wckeys")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseWckeyAdd{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Delete account

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `account_name` (String.t): Slurm Account Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseAccountDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_delete_account(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ResponseAccountDelete.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_delete_account(connection, account_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.38/account/#{account_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseAccountDelete{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Delete association

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:cluster` (String.t): Cluster name
    - `:account` (String.t): Account name
    - `:user` (String.t): User name
    - `:partition` (String.t): Partition Name

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseAssociationsDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_delete_association(Tesla.Env.client, keyword()) :: {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:ok, SlurmRestAPI.Model.Dbv0038ResponseAssociationsDelete.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_delete_association(connection, opts \\ []) do
    optional_params = %{
      :cluster => :query,
      :account => :query,
      :user => :query,
      :partition => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.38/association")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseAssociationsDelete{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Delete associations

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:cluster` (String.t): Cluster name
    - `:account` (String.t): Account name
    - `:user` (String.t): User name
    - `:partition` (String.t): Partition Name

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseAssociationsDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_delete_associations(Tesla.Env.client, keyword()) :: {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:ok, SlurmRestAPI.Model.Dbv0038ResponseAssociationsDelete.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_delete_associations(connection, opts \\ []) do
    optional_params = %{
      :cluster => :query,
      :account => :query,
      :user => :query,
      :partition => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.38/associations")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseAssociationsDelete{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Delete cluster

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `cluster_name` (String.t): Slurm cluster name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseClusterDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_delete_cluster(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ResponseClusterDelete.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_delete_cluster(connection, cluster_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.38/cluster/#{cluster_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseClusterDelete{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Delete QOS

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `qos_name` (String.t): Slurm QOS Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseQosDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_delete_qos(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ResponseQosDelete.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_delete_qos(connection, qos_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.38/qos/#{qos_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseQosDelete{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Delete user

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `user_name` (String.t): Slurm User Name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseUserDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_delete_user(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ResponseUserDelete.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_delete_user(connection, user_name, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.38/user/#{user_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseUserDelete{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Delete wckey

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `wckey` (String.t): Slurm wckey name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseWckeyDelete.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_delete_wckey(Tesla.Env.client, String.t, keyword()) :: {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:ok, SlurmRestAPI.Model.Dbv0038ResponseWckeyDelete.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_delete_wckey(connection, wckey, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/slurmdb/v0.0.38/wckey/#{wckey}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseWckeyDelete{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get slurmdb diagnostics

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038Diag.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_diag(Tesla.Env.client, keyword()) :: {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:ok, SlurmRestAPI.Model.Dbv0038Diag.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_diag(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/diag")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038Diag{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get account info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `account_name` (String.t): Slurm Account Name
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (boolean()): Include deleted accounts. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038AccountInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_account(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038AccountInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_account(connection, account_name, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/account/#{account_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038AccountInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get account list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (boolean()): Include deleted accounts. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038AccountInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_accounts(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038AccountInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_accounts(connection, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/accounts")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038AccountInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get association info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:cluster` (String.t): Cluster name
    - `:account` (String.t): Account name
    - `:user` (String.t): User name
    - `:partition` (String.t): Partition Name

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038AssociationsInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_association(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038AssociationsInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_association(connection, opts \\ []) do
    optional_params = %{
      :cluster => :query,
      :account => :query,
      :user => :query,
      :partition => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/association")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038AssociationsInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get association list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:cluster` (String.t): Cluster name
    - `:account` (String.t): Account name
    - `:user` (String.t): User name
    - `:partition` (String.t): Partition Name

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038AssociationsInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_associations(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038AssociationsInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_associations(connection, opts \\ []) do
    optional_params = %{
      :cluster => :query,
      :account => :query,
      :user => :query,
      :partition => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/associations")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038AssociationsInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get cluster info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `cluster_name` (String.t): Slurm cluster name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ClusterInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_cluster(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ClusterInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_cluster(connection, cluster_name, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/cluster/#{cluster_name}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ClusterInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get cluster list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ClusterInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_clusters(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ClusterInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_clusters(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/clusters")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ClusterInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Dump all configuration information

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ConfigInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_config(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ConfigInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_config(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/config")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ConfigInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get job info
  This endpoint may return multiple job entries since job_id is not a unique key - only the tuple (cluster, job_id, start_time) is unique. If the requested job_id is a component of a heterogeneous job all components are returned.

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `job_id` (String.t): Slurm JobID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038JobInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_job(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038JobInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_job(connection, job_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/job/#{job_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038JobInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get job list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:submit_time` (String.t): Filter by submission time  Accepted formats:  HH:MM[:SS] [AM|PM]  MMDD[YY] or MM/DD[/YY] or MM.DD[.YY]  MM/DD[/YY]-HH:MM[:SS]  YYYY-MM-DD[THH:MM[:SS]]
    - `:start_time` (String.t): Filter by start time  Accepted formats:  HH:MM[:SS] [AM|PM]  MMDD[YY] or MM/DD[/YY] or MM.DD[.YY]  MM/DD[/YY]-HH:MM[:SS]  YYYY-MM-DD[THH:MM[:SS]]
    - `:end_time` (String.t): Filter by end time  Accepted formats:  HH:MM[:SS] [AM|PM]  MMDD[YY] or MM/DD[/YY] or MM.DD[.YY]  MM/DD[/YY]-HH:MM[:SS]  YYYY-MM-DD[THH:MM[:SS]]
    - `:account` (String.t): Comma delimited list of accounts to match
    - `:association` (String.t): Comma delimited list of associations to match
    - `:cluster` (String.t): Comma delimited list of cluster to match
    - `:constraints` (String.t): Comma delimited list of constraints to match
    - `:cpus_max` (String.t): Number of CPUs high range
    - `:cpus_min` (String.t): Number of CPUs low range
    - `:skip_steps` (boolean()): Report job step information
    - `:disable_wait_for_result` (boolean()): Disable waiting for result from slurmdbd
    - `:exit_code` (String.t): Exit code of job
    - `:format` (String.t): Comma delimited list of formats to match
    - `:group` (String.t): Comma delimited list of groups to match
    - `:job_name` (String.t): Comma delimited list of job names to match
    - `:nodes_max` (String.t): Number of nodes high range
    - `:nodes_min` (String.t): Number of nodes low range
    - `:partition` (String.t): Comma delimited list of partitions to match
    - `:qos` (String.t): Comma delimited list of QOS to match
    - `:reason` (String.t): Comma delimited list of job reasons to match
    - `:reservation` (String.t): Comma delimited list of reservations to match
    - `:state` (String.t): Comma delimited list of states to match
    - `:step` (String.t): Comma delimited list of job steps to match
    - `:node` (String.t): Comma delimited list of used nodes to match
    - `:wckey` (String.t): Comma delimited list of wckeys to match

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038JobInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_jobs(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038JobInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_jobs(connection, opts \\ []) do
    optional_params = %{
      :submit_time => :query,
      :start_time => :query,
      :end_time => :query,
      :account => :query,
      :association => :query,
      :cluster => :query,
      :constraints => :query,
      :cpus_max => :query,
      :cpus_min => :query,
      :skip_steps => :query,
      :disable_wait_for_result => :query,
      :exit_code => :query,
      :format => :query,
      :group => :query,
      :job_name => :query,
      :nodes_max => :query,
      :nodes_min => :query,
      :partition => :query,
      :qos => :query,
      :reason => :query,
      :reservation => :query,
      :state => :query,
      :step => :query,
      :node => :query,
      :wckey => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/jobs")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038JobInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get QOS list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (boolean()): Include deleted QOSs. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038QosInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_qos(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038QosInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_qos(connection, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/qos")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038QosInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get QOS info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `qos_name` (String.t): Slurm QOS Name
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (boolean()): Include deleted QOSs. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038QosInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_single_qos(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038QosInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_single_qos(connection, qos_name, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/qos/#{qos_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038QosInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get TRES info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038TresInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_tres(Tesla.Env.client, keyword()) :: {:ok, nil} | {:ok, SlurmRestAPI.Model.Dbv0038TresInfo.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_tres(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/tres")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038TresInfo{}},
      {:default, false}
    ])
  end

  @doc """
  Get user info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `user_name` (String.t): Slurm User Name
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (boolean()): Include deleted users. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038UserInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_user(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038UserInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_user(connection, user_name, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/user/#{user_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038UserInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get user list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:with_deleted` (boolean()): Include deleted users. False by default.

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038UserInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_users(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038UserInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_users(connection, opts \\ []) do
    optional_params = %{
      :with_deleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/users")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038UserInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get wckey info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `wckey` (String.t): Slurm wckey name
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038WckeyInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_wckey(Tesla.Env.client, String.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038WckeyInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_wckey(connection, wckey, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/wckey/#{wckey}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038WckeyInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Get wckey list

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038WckeyInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_get_wckeys(Tesla.Env.client, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038WckeyInfo.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_get_wckeys(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/slurmdb/v0.0.38/wckeys")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038WckeyInfo{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Load all configuration information

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (Dbv0038SetConfig): Add or update config

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ConfigResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_set_config(Tesla.Env.client, keyword()) :: {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:ok, SlurmRestAPI.Model.Dbv0038ConfigResponse.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_set_config(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.38/config")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ConfigResponse{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Update accounts

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0038_update_account` (Dbv0038UpdateAccount): update/create accounts
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038AccountResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_update_account(Tesla.Env.client, SlurmRestAPI.Model.Dbv0038UpdateAccount.t, keyword()) :: {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:ok, SlurmRestAPI.Model.Dbv0038AccountResponse.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_update_account(connection, dbv0038_update_account, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.38/accounts")
      |> add_param(:body, :body, dbv0038_update_account)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038AccountResponse{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Set associations info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0038_associations_info` (Dbv0038AssociationsInfo): Add or update associations
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseAssociations.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_update_associations(Tesla.Env.client, SlurmRestAPI.Model.Dbv0038AssociationsInfo.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ResponseAssociations.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_update_associations(connection, dbv0038_associations_info, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.38/associations")
      |> add_param(:body, :body, dbv0038_associations_info)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseAssociations{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Set QOS info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0038_update_qos` (Dbv0038UpdateQos): Add or update QOSs
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseQos.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_update_qos(Tesla.Env.client, SlurmRestAPI.Model.Dbv0038UpdateQos.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ResponseQos.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_update_qos(connection, dbv0038_update_qos, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.38/qos")
      |> add_param(:body, :body, dbv0038_update_qos)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseQos{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Set TRES info

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0038_tres_update` (Dbv0038TresUpdate): Add or Update TRES
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseTres.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_update_tres(Tesla.Env.client, SlurmRestAPI.Model.Dbv0038TresUpdate.t, keyword()) :: {:ok, SlurmRestAPI.Model.Dbv0038ResponseTres.t} | {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:error, Tesla.Env.t}
  def slurmdb_v0038_update_tres(connection, dbv0038_tres_update, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.38/tres")
      |> add_param(:body, :body, dbv0038_tres_update)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseTres{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end

  @doc """
  Update user

  ### Parameters

  - `connection` (SlurmRestAPI.Connection): Connection to server
  - `dbv0038_update_users` (Dbv0038UpdateUsers): add or update user
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, SlurmRestAPI.Model.Dbv0038ResponseUserUpdate.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec slurmdb_v0038_update_users(Tesla.Env.client, SlurmRestAPI.Model.Dbv0038UpdateUsers.t, keyword()) :: {:ok, list(SlurmRestAPI.Model.Dbv0038Error.t)} | {:ok, SlurmRestAPI.Model.Dbv0038ResponseUserUpdate.t} | {:error, Tesla.Env.t}
  def slurmdb_v0038_update_users(connection, dbv0038_update_users, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/slurmdb/v0.0.38/users")
      |> add_param(:body, :body, dbv0038_update_users)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %SlurmRestAPI.Model.Dbv0038ResponseUserUpdate{}},
      {:default, [%SlurmRestAPI.Model.Dbv0038Error{}]}
    ])
  end
end
