# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.Dbv0039MetaSlurm do
  @moduledoc """
  Slurm information
  """

  @derive Jason.Encoder
  defstruct [
    :version,
    :release
  ]

  @type t :: %__MODULE__{
    :version => SlurmRESTAPI.Model.Dbv0039MetaSlurmVersion.t | nil,
    :release => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:version, :struct, SlurmRESTAPI.Model.Dbv0039MetaSlurmVersion)
  end
end

