# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.Dbv0039MetaPlugin do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :name
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :name => String.t | nil
  }

  def decode(value) do
    value
  end
end

