# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.Dbv0039ConfigInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :meta,
    :errors,
    :warnings,
    :tres,
    :accounts,
    :associations,
    :users,
    :qos,
    :wckeys,
    :clusters
  ]

  @type t :: %__MODULE__{
    :meta => SlurmRESTAPI.Model.Dbv0039Meta.t | nil,
    :errors => [SlurmRESTAPI.Model.Dbv0039Error.t] | nil,
    :warnings => [SlurmRESTAPI.Model.Dbv0039Warning.t] | nil,
    :tres => [SlurmRESTAPI.Model.V0039Tres.t] | nil,
    :accounts => [SlurmRESTAPI.Model.V0039Account.t] | nil,
    :associations => [SlurmRESTAPI.Model.V0039Assoc.t] | nil,
    :users => [SlurmRESTAPI.Model.V0039User.t] | nil,
    :qos => [SlurmRESTAPI.Model.V0039Qos.t] | nil,
    :wckeys => [SlurmRESTAPI.Model.V0039Wckey.t] | nil,
    :clusters => [SlurmRESTAPI.Model.V0039ClusterRec.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:meta, :struct, SlurmRESTAPI.Model.Dbv0039Meta)
     |> Deserializer.deserialize(:errors, :list, SlurmRESTAPI.Model.Dbv0039Error)
     |> Deserializer.deserialize(:warnings, :list, SlurmRESTAPI.Model.Dbv0039Warning)
     |> Deserializer.deserialize(:tres, :list, SlurmRESTAPI.Model.V0039Tres)
     |> Deserializer.deserialize(:accounts, :list, SlurmRESTAPI.Model.V0039Account)
     |> Deserializer.deserialize(:associations, :list, SlurmRESTAPI.Model.V0039Assoc)
     |> Deserializer.deserialize(:users, :list, SlurmRESTAPI.Model.V0039User)
     |> Deserializer.deserialize(:qos, :list, SlurmRESTAPI.Model.V0039Qos)
     |> Deserializer.deserialize(:wckeys, :list, SlurmRESTAPI.Model.V0039Wckey)
     |> Deserializer.deserialize(:clusters, :list, SlurmRESTAPI.Model.V0039ClusterRec)
  end
end

