# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.Dbv0039SetConfig do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :clusters,
    :TRES,
    :accounts,
    :users,
    :qos,
    :wckeys,
    :associations
  ]

  @type t :: %__MODULE__{
    :clusters => [SlurmRESTAPI.Model.V0039ClusterRec.t] | nil,
    :TRES => [SlurmRESTAPI.Model.List.t] | nil,
    :accounts => [SlurmRESTAPI.Model.V0039Account.t] | nil,
    :users => [SlurmRESTAPI.Model.V0039User.t] | nil,
    :qos => [SlurmRESTAPI.Model.V0039Qos.t] | nil,
    :wckeys => [SlurmRESTAPI.Model.V0039Wckey.t] | nil,
    :associations => [SlurmRESTAPI.Model.V0039Assoc.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:clusters, :list, SlurmRESTAPI.Model.V0039ClusterRec)
     |> Deserializer.deserialize(:accounts, :list, SlurmRESTAPI.Model.V0039Account)
     |> Deserializer.deserialize(:users, :list, SlurmRESTAPI.Model.V0039User)
     |> Deserializer.deserialize(:qos, :list, SlurmRESTAPI.Model.V0039Qos)
     |> Deserializer.deserialize(:wckeys, :list, SlurmRESTAPI.Model.V0039Wckey)
     |> Deserializer.deserialize(:associations, :list, SlurmRESTAPI.Model.V0039Assoc)
  end
end

