# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040UserDefault do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account,
    :wckey
  ]

  @type t :: %__MODULE__{
    :account => String.t | nil,
    :wckey => String.t | nil
  }

  def decode(value) do
    value
  end
end

