# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :flags,
    :id,
    :limits,
    :name,
    :preempt,
    :priority,
    :usage_factor,
    :usage_threshold
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :flags => [String.t] | nil,
    :id => integer() | nil,
    :limits => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimits.t | nil,
    :name => String.t | nil,
    :preempt => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerPreempt.t | nil,
    :priority => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerPriority.t | nil,
    :usage_factor => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerUsageFactor.t | nil,
    :usage_threshold => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerUsageThreshold.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:limits, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimits)
     |> Deserializer.deserialize(:preempt, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerPreempt)
     |> Deserializer.deserialize(:priority, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerPriority)
     |> Deserializer.deserialize(:usage_factor, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerUsageFactor)
     |> Deserializer.deserialize(:usage_threshold, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerUsageThreshold)
  end
end

