# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiDiagRespStatisticsRpcsByUserInner do
  @moduledoc """
  RPCs by user
  """

  @derive Jason.Encoder
  defstruct [
    :user_id,
    :user,
    :count,
    :total_time,
    :average_time
  ]

  @type t :: %__MODULE__{
    :user_id => integer(),
    :user => String.t,
    :count => integer(),
    :total_time => integer(),
    :average_time => SlurmRESTAPI.Model.V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInnerAverageTime.t
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:average_time, :struct, SlurmRESTAPI.Model.V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInnerAverageTime)
  end
end

