# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiAccountsAddCondRespAccount do
  @moduledoc """
  Account organization and description
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :organization
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :organization => String.t | nil
  }

  def decode(value) do
    value
  end
end

