# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040OpenapiUsersResp do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :users,
    :meta,
    :errors,
    :warnings
  ]

  @type t :: %__MODULE__{
    :users => [SlurmRESTAPI.Model.V0040User.t],
    :meta => SlurmRESTAPI.Model.V0040OpenapiMeta.t | nil,
    :errors => [SlurmRESTAPI.Model.V0040OpenapiError.t] | nil,
    :warnings => [SlurmRESTAPI.Model.V0040OpenapiWarning.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:users, :list, SlurmRESTAPI.Model.V0040User)
     |> Deserializer.deserialize(:meta, :struct, SlurmRESTAPI.Model.V0040OpenapiMeta)
     |> Deserializer.deserialize(:errors, :list, SlurmRESTAPI.Model.V0040OpenapiError)
     |> Deserializer.deserialize(:warnings, :list, SlurmRESTAPI.Model.V0040OpenapiWarning)
  end
end

