# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039QosLimits do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :grace_time,
    :max,
    :factor,
    :min
  ]

  @type t :: %__MODULE__{
    :grace_time => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil,
    :max => SlurmRESTAPI.Model.V0039QosLimitsMax.t | nil,
    :factor => float() | nil,
    :min => SlurmRESTAPI.Model.V0039QosLimitsMin.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:grace_time, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
     |> Deserializer.deserialize(:max, :struct, SlurmRESTAPI.Model.V0039QosLimitsMax)
     |> Deserializer.deserialize(:min, :struct, SlurmRESTAPI.Model.V0039QosLimitsMin)
  end
end

