# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInnerTres do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :run_seconds,
    :group_minutes,
    :usage
  ]

  @type t :: %__MODULE__{
    :run_seconds => [SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInner.t] | nil,
    :group_minutes => [SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInner.t] | nil,
    :usage => [SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInnerTresUsageInner.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:run_seconds, :list, SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInner)
     |> Deserializer.deserialize(:group_minutes, :list, SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInnerTresRunSecondsInner)
     |> Deserializer.deserialize(:usage, :list, SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInnerTresUsageInner)
  end
end

