# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040JobArrayLimits do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :max
  ]

  @type t :: %__MODULE__{
    :max => SlurmRESTAPI.Model.V0040JobArrayLimitsMax.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:max, :struct, SlurmRESTAPI.Model.V0040JobArrayLimitsMax)
  end
end

