# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name
  ]

  @type t :: %__MODULE__{
    :id => SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignalId.t | nil,
    :name => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:id, :struct, SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignalId)
  end
end

