# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039JobComment do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :administrator,
    :job,
    :system
  ]

  @type t :: %__MODULE__{
    :administrator => String.t | nil,
    :job => String.t | nil,
    :system => String.t | nil
  }

  def decode(value) do
    value
  end
end

