# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040ReservationCoreSpec do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :node,
    :core
  ]

  @type t :: %__MODULE__{
    :node => String.t | nil,
    :core => String.t | nil
  }

  def decode(value) do
    value
  end
end

