# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespUsersInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :administrator_level,
    :associations,
    :coordinators,
    :default,
    :flags,
    :name,
    :old_name,
    :wckeys
  ]

  @type t :: %__MODULE__{
    :administrator_level => [String.t] | nil,
    :associations => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAccountsInnerAssociationsInner.t] | nil,
    :coordinators => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAccountsInnerCoordinatorsInner.t] | nil,
    :default => SlurmRESTAPI.Model.V0040UserDefault.t | nil,
    :flags => [String.t] | nil,
    :name => String.t,
    :old_name => String.t | nil,
    :wckeys => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInner.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:associations, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAccountsInnerAssociationsInner)
     |> Deserializer.deserialize(:coordinators, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAccountsInnerCoordinatorsInner)
     |> Deserializer.deserialize(:default, :struct, SlurmRESTAPI.Model.V0040UserDefault)
     |> Deserializer.deserialize(:wckeys, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInner)
  end
end

