# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040UpdateNodeMsg do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :comment,
    :cpu_bind,
    :extra,
    :features,
    :features_act,
    :gres,
    :address,
    :hostname,
    :name,
    :state,
    :reason,
    :reason_uid,
    :resume_after,
    :weight
  ]

  @type t :: %__MODULE__{
    :comment => String.t | nil,
    :cpu_bind => integer() | nil,
    :extra => String.t | nil,
    :features => [String.t] | nil,
    :features_act => [String.t] | nil,
    :gres => String.t | nil,
    :address => [String.t] | nil,
    :hostname => [String.t] | nil,
    :name => [String.t] | nil,
    :state => [String.t] | nil,
    :reason => String.t | nil,
    :reason_uid => String.t | nil,
    :resume_after => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :weight => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:resume_after, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:weight, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
  end
end

