# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039ClusterRec do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :controller,
    :flags,
    :name,
    :nodes,
    :select_plugin,
    :associations,
    :rpc_version,
    :tres
  ]

  @type t :: %__MODULE__{
    :controller => SlurmRESTAPI.Model.V0039ClusterRecController.t | nil,
    :flags => [String.t] | nil,
    :name => String.t | nil,
    :nodes => String.t | nil,
    :select_plugin => String.t | nil,
    :associations => SlurmRESTAPI.Model.V0039ClusterRecAssociations.t | nil,
    :rpc_version => integer() | nil,
    :tres => [SlurmRESTAPI.Model.V0039Tres.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:controller, :struct, SlurmRESTAPI.Model.V0039ClusterRecController)
     |> Deserializer.deserialize(:associations, :struct, SlurmRESTAPI.Model.V0039ClusterRecAssociations)
     |> Deserializer.deserialize(:tres, :list, SlurmRESTAPI.Model.V0039Tres)
  end
end

