# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040AssocMax do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :jobs,
    :tres,
    :per
  ]

  @type t :: %__MODULE__{
    :jobs => SlurmRESTAPI.Model.V0040AssocMaxJobs.t | nil,
    :tres => SlurmRESTAPI.Model.V0040AssocMaxTres.t | nil,
    :per => SlurmRESTAPI.Model.V0040AssocMaxPer.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:jobs, :struct, SlurmRESTAPI.Model.V0040AssocMaxJobs)
     |> Deserializer.deserialize(:tres, :struct, SlurmRESTAPI.Model.V0040AssocMaxTres)
     |> Deserializer.deserialize(:per, :struct, SlurmRESTAPI.Model.V0040AssocMaxPer)
  end
end

