# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040StatsMsgRpcsByUserInner do
  @moduledoc """
  user
  """

  @derive Jason.Encoder
  defstruct [
    :user,
    :user_id,
    :count,
    :average_time,
    :total_time
  ]

  @type t :: %__MODULE__{
    :user => String.t | nil,
    :user_id => integer() | nil,
    :count => integer() | nil,
    :average_time => integer() | nil,
    :total_time => integer() | nil
  }

  def decode(value) do
    value
  end
end

