# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041JobDescMsgRlimits do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :cpu,
    :fsize,
    :data,
    :stack,
    :core,
    :rss,
    :nproc,
    :nofile,
    :memlock,
    :as
  ]

  @type t :: %__MODULE__{
    :cpu => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsCpu.t | nil,
    :fsize => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsFsize.t | nil,
    :data => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsData.t | nil,
    :stack => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsStack.t | nil,
    :core => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsCore.t | nil,
    :rss => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsRss.t | nil,
    :nproc => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsNproc.t | nil,
    :nofile => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsNofile.t | nil,
    :memlock => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsMemlock.t | nil,
    :as => SlurmRESTAPI.Model.V0041JobDescMsgRlimitsAs.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cpu, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsCpu)
     |> Deserializer.deserialize(:fsize, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsFsize)
     |> Deserializer.deserialize(:data, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsData)
     |> Deserializer.deserialize(:stack, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsStack)
     |> Deserializer.deserialize(:core, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsCore)
     |> Deserializer.deserialize(:rss, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsRss)
     |> Deserializer.deserialize(:nproc, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsNproc)
     |> Deserializer.deserialize(:nofile, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsNofile)
     |> Deserializer.deserialize(:memlock, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsMemlock)
     |> Deserializer.deserialize(:as, :struct, SlurmRESTAPI.Model.V0041JobDescMsgRlimitsAs)
  end
end

