# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :accounts,
    :burst_buffer,
    :core_count,
    :core_specializations,
    :end_time,
    :features,
    :flags,
    :groups,
    :licenses,
    :max_start_delay,
    :name,
    :node_count,
    :node_list,
    :partition,
    :purge_completed,
    :start_time,
    :watts,
    :tres,
    :users
  ]

  @type t :: %__MODULE__{
    :accounts => String.t | nil,
    :burst_buffer => String.t | nil,
    :core_count => integer() | nil,
    :core_specializations => [SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerCoreSpecializationsInner.t] | nil,
    :end_time => SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerEndTime.t | nil,
    :features => String.t | nil,
    :flags => [String.t] | nil,
    :groups => String.t | nil,
    :licenses => String.t | nil,
    :max_start_delay => integer() | nil,
    :name => String.t | nil,
    :node_count => integer() | nil,
    :node_list => String.t | nil,
    :partition => String.t | nil,
    :purge_completed => SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerPurgeCompleted.t | nil,
    :start_time => SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerStartTime.t | nil,
    :watts => SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerWatts.t | nil,
    :tres => String.t | nil,
    :users => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:core_specializations, :list, SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerCoreSpecializationsInner)
     |> Deserializer.deserialize(:end_time, :struct, SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerEndTime)
     |> Deserializer.deserialize(:purge_completed, :struct, SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerPurgeCompleted)
     |> Deserializer.deserialize(:start_time, :struct, SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerStartTime)
     |> Deserializer.deserialize(:watts, :struct, SlurmRESTAPI.Model.V0041OpenapiReservationRespReservationsInnerWatts)
  end
end

