# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039AssocMaxJobsPer do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :accruing,
    :submitted,
    :wall_clock
  ]

  @type t :: %__MODULE__{
    :count => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil,
    :accruing => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil,
    :submitted => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil,
    :wall_clock => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:count, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
     |> Deserializer.deserialize(:accruing, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
     |> Deserializer.deserialize(:submitted, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
     |> Deserializer.deserialize(:wall_clock, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
  end
end

