# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatistics do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :CPU,
    :energy
  ]

  @type t :: %__MODULE__{
    :CPU => SlurmRESTAPI.Model.V0040StepStatisticsCpu.t | nil,
    :energy => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsEnergy.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:CPU, :struct, SlurmRESTAPI.Model.V0040StepStatisticsCpu)
     |> Deserializer.deserialize(:energy, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatisticsEnergy)
  end
end

