# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039QosPreempt do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :list,
    :mode,
    :exempt_time
  ]

  @type t :: %__MODULE__{
    :list => [String.t] | nil,
    :mode => [String.t] | nil,
    :exempt_time => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:exempt_time, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
  end
end

