# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040JobState do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :current,
    :reason
  ]

  @type t :: %__MODULE__{
    :current => [String.t] | nil,
    :reason => String.t | nil
  }

  def decode(value) do
    value
  end
end

