# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040JobHet do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :job_id,
    :job_offset
  ]

  @type t :: %__MODULE__{
    :job_id => integer() | nil,
    :job_offset => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:job_offset, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
  end
end

