# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040OpenapiWarning do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :source
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :source => String.t | nil
  }

  def decode(value) do
    value
  end
end

