# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040OpenapiMetaSlurm do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :version,
    :release,
    :cluster
  ]

  @type t :: %__MODULE__{
    :version => SlurmRESTAPI.Model.V0040OpenapiMetaSlurmVersion.t | nil,
    :release => String.t | nil,
    :cluster => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:version, :struct, SlurmRESTAPI.Model.V0040OpenapiMetaSlurmVersion)
  end
end

