# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039JobSubmission do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :script,
    :job,
    :jobs
  ]

  @type t :: %__MODULE__{
    :script => String.t | nil,
    :job => SlurmRESTAPI.Model.V0039JobDescMsg.t | nil,
    :jobs => [SlurmRESTAPI.Model.V0039JobDescMsg.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:job, :struct, SlurmRESTAPI.Model.V0039JobDescMsg)
     |> Deserializer.deserialize(:jobs, :list, SlurmRESTAPI.Model.V0039JobDescMsg)
  end
end

