# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMax do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :active_jobs,
    :tres,
    :wall_clock,
    :jobs,
    :accruing
  ]

  @type t :: %__MODULE__{
    :active_jobs => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobs.t | nil,
    :tres => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxTres.t | nil,
    :wall_clock => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxWallClock.t | nil,
    :jobs => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobs.t | nil,
    :accruing => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxAccruing.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:active_jobs, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobs)
     |> Deserializer.deserialize(:tres, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxTres)
     |> Deserializer.deserialize(:wall_clock, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxWallClock)
     |> Deserializer.deserialize(:jobs, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobs)
     |> Deserializer.deserialize(:accruing, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxAccruing)
  end
end

