# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobs do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :active_jobs,
    :per
  ]

  @type t :: %__MODULE__{
    :active_jobs => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsActiveJobs.t | nil,
    :per => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsPer.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:active_jobs, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsActiveJobs)
     |> Deserializer.deserialize(:per, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsPer)
  end
end

