# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039PartitionInfoDefaults do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :memory_per_cpu,
    :time,
    :job
  ]

  @type t :: %__MODULE__{
    :memory_per_cpu => integer() | nil,
    :time => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil,
    :job => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:time, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
  end
end

