# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040OpenapiMetaPlugin do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :name,
    :data_parser,
    :accounting_storage
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :name => String.t | nil,
    :data_parser => String.t | nil,
    :accounting_storage => String.t | nil
  }

  def decode(value) do
    value
  end
end

