# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039JobArray do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :job_id,
    :limits,
    :task_id,
    :task
  ]

  @type t :: %__MODULE__{
    :job_id => integer() | nil,
    :limits => SlurmRESTAPI.Model.V0039JobArrayLimits.t | nil,
    :task_id => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil,
    :task => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:limits, :struct, SlurmRESTAPI.Model.V0039JobArrayLimits)
     |> Deserializer.deserialize(:task_id, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
  end
end

