# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040CronEntryLine do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :start,
    :end
  ]

  @type t :: %__MODULE__{
    :start => integer() | nil,
    :end => integer() | nil
  }

  def decode(value) do
    value
  end
end

