# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039AssocMaxTresGroup do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :minutes,
    :active
  ]

  @type t :: %__MODULE__{
    :minutes => [SlurmRESTAPI.Model.V0039Tres.t] | nil,
    :active => [SlurmRESTAPI.Model.V0039Tres.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:minutes, :list, SlurmRESTAPI.Model.V0039Tres)
     |> Deserializer.deserialize(:active, :list, SlurmRESTAPI.Model.V0039Tres)
  end
end

