# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040OpenapiMeta do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :plugin,
    :client,
    :command,
    :slurm
  ]

  @type t :: %__MODULE__{
    :plugin => SlurmRESTAPI.Model.V0040OpenapiMetaPlugin.t | nil,
    :client => SlurmRESTAPI.Model.V0040OpenapiMetaClient.t | nil,
    :command => [String.t] | nil,
    :slurm => SlurmRESTAPI.Model.V0040OpenapiMetaSlurm.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:plugin, :struct, SlurmRESTAPI.Model.V0040OpenapiMetaPlugin)
     |> Deserializer.deserialize(:client, :struct, SlurmRESTAPI.Model.V0040OpenapiMetaClient)
     |> Deserializer.deserialize(:slurm, :struct, SlurmRESTAPI.Model.V0040OpenapiMetaSlurm)
  end
end

