# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResources do
  @moduledoc """
  Resources used by the job
  """

  @derive Jason.Encoder
  defstruct [
    :select_type,
    :nodes,
    :cpus,
    :threads_per_core
  ]

  @type t :: %__MODULE__{
    :select_type => [String.t],
    :nodes => SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodes.t | nil,
    :cpus => integer(),
    :threads_per_core => SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesThreadsPerCore.t
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:nodes, :struct, SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodes)
     |> Deserializer.deserialize(:threads_per_core, :struct, SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesThreadsPerCore)
  end
end

