# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041JobAllocReq do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :hetjob,
    :job
  ]

  @type t :: %__MODULE__{
    :hetjob => [SlurmRESTAPI.Model.V0041JobDescMsg.t] | nil,
    :job => SlurmRESTAPI.Model.V0041JobDescMsg.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:hetjob, :list, SlurmRESTAPI.Model.V0041JobDescMsg)
     |> Deserializer.deserialize(:job, :struct, SlurmRESTAPI.Model.V0041JobDescMsg)
  end
end

