# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :nodes,
    :accounts,
    :groups,
    :qos,
    :alternate,
    :tres,
    :cluster,
    :select_type,
    :cpus,
    :defaults,
    :grace_time,
    :maximums,
    :minimums,
    :name,
    :node_sets,
    :priority,
    :timeouts,
    :partition,
    :suspend_time
  ]

  @type t :: %__MODULE__{
    :nodes => SlurmRESTAPI.Model.V0040PartitionInfoNodes.t | nil,
    :accounts => SlurmRESTAPI.Model.V0040PartitionInfoAccounts.t | nil,
    :groups => SlurmRESTAPI.Model.V0040PartitionInfoGroups.t | nil,
    :qos => SlurmRESTAPI.Model.V0040PartitionInfoQos.t | nil,
    :alternate => String.t | nil,
    :tres => SlurmRESTAPI.Model.V0040PartitionInfoTres.t | nil,
    :cluster => String.t | nil,
    :select_type => [String.t] | nil,
    :cpus => SlurmRESTAPI.Model.V0040PartitionInfoCpus.t | nil,
    :defaults => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaults.t | nil,
    :grace_time => integer() | nil,
    :maximums => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximums.t | nil,
    :minimums => SlurmRESTAPI.Model.V0040PartitionInfoMinimums.t | nil,
    :name => String.t | nil,
    :node_sets => String.t | nil,
    :priority => SlurmRESTAPI.Model.V0040PartitionInfoPriority.t | nil,
    :timeouts => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerTimeouts.t | nil,
    :partition => SlurmRESTAPI.Model.V0040PartitionInfoPartition.t | nil,
    :suspend_time => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerSuspendTime.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:nodes, :struct, SlurmRESTAPI.Model.V0040PartitionInfoNodes)
     |> Deserializer.deserialize(:accounts, :struct, SlurmRESTAPI.Model.V0040PartitionInfoAccounts)
     |> Deserializer.deserialize(:groups, :struct, SlurmRESTAPI.Model.V0040PartitionInfoGroups)
     |> Deserializer.deserialize(:qos, :struct, SlurmRESTAPI.Model.V0040PartitionInfoQos)
     |> Deserializer.deserialize(:tres, :struct, SlurmRESTAPI.Model.V0040PartitionInfoTres)
     |> Deserializer.deserialize(:cpus, :struct, SlurmRESTAPI.Model.V0040PartitionInfoCpus)
     |> Deserializer.deserialize(:defaults, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaults)
     |> Deserializer.deserialize(:maximums, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximums)
     |> Deserializer.deserialize(:minimums, :struct, SlurmRESTAPI.Model.V0040PartitionInfoMinimums)
     |> Deserializer.deserialize(:priority, :struct, SlurmRESTAPI.Model.V0040PartitionInfoPriority)
     |> Deserializer.deserialize(:timeouts, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerTimeouts)
     |> Deserializer.deserialize(:partition, :struct, SlurmRESTAPI.Model.V0040PartitionInfoPartition)
     |> Deserializer.deserialize(:suspend_time, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerSuspendTime)
  end
end

