# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040JobTres do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :allocated,
    :requested
  ]

  @type t :: %__MODULE__{
    :allocated => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :requested => [SlurmRESTAPI.Model.V0040Tres.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:allocated, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:requested, :list, SlurmRESTAPI.Model.V0040Tres)
  end
end

