# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxTres do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :total,
    :minutes,
    :per
  ]

  @type t :: %__MODULE__{
    :total => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :minutes => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxTresMinutes.t | nil,
    :per => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxTresPer.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:total, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:minutes, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxTresMinutes)
     |> Deserializer.deserialize(:per, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxTresPer)
  end
end

