# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040StepCpuRequestedFrequency do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :min,
    :max
  ]

  @type t :: %__MODULE__{
    :min => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :max => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:min, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:max, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
  end
end

