# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039Account do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :associations,
    :coordinators,
    :description,
    :name,
    :organization,
    :flags
  ]

  @type t :: %__MODULE__{
    :associations => [SlurmRESTAPI.Model.V0039AssocShort.t] | nil,
    :coordinators => [SlurmRESTAPI.Model.V0039Coord.t] | nil,
    :description => String.t,
    :name => String.t,
    :organization => String.t,
    :flags => [String.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:associations, :list, SlurmRESTAPI.Model.V0039AssocShort)
     |> Deserializer.deserialize(:coordinators, :list, SlurmRESTAPI.Model.V0039Coord)
  end
end

