# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039StatsRpcTime do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :average,
    :total
  ]

  @type t :: %__MODULE__{
    :average => integer() | nil,
    :total => integer() | nil
  }

  def decode(value) do
    value
  end
end

