# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsPer do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account,
    :user
  ]

  @type t :: %__MODULE__{
    :account => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsPerAccount.t | nil,
    :user => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsPerUser.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:account, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsPerAccount)
     |> Deserializer.deserialize(:user, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxJobsPerUser)
  end
end

