# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040JobInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account,
    :accrue_time,
    :admin_comment,
    :allocating_node,
    :array_job_id,
    :array_task_id,
    :array_max_tasks,
    :array_task_string,
    :association_id,
    :batch_features,
    :batch_flag,
    :batch_host,
    :flags,
    :burst_buffer,
    :burst_buffer_state,
    :cluster,
    :cluster_features,
    :command,
    :comment,
    :container,
    :container_id,
    :contiguous,
    :core_spec,
    :thread_spec,
    :cores_per_socket,
    :billable_tres,
    :cpus_per_task,
    :cpu_frequency_minimum,
    :cpu_frequency_maximum,
    :cpu_frequency_governor,
    :cpus_per_tres,
    :cron,
    :deadline,
    :delay_boot,
    :dependency,
    :derived_exit_code,
    :eligible_time,
    :end_time,
    :excluded_nodes,
    :exit_code,
    :extra,
    :failed_node,
    :features,
    :federation_origin,
    :federation_siblings_active,
    :federation_siblings_viable,
    :gres_detail,
    :group_id,
    :group_name,
    :het_job_id,
    :het_job_id_set,
    :het_job_offset,
    :job_id,
    :job_resources,
    :job_size_str,
    :job_state,
    :last_sched_evaluation,
    :licenses,
    :mail_type,
    :mail_user,
    :max_cpus,
    :max_nodes,
    :mcs_label,
    :memory_per_tres,
    :name,
    :network,
    :nodes,
    :nice,
    :tasks_per_core,
    :tasks_per_tres,
    :tasks_per_node,
    :tasks_per_socket,
    :tasks_per_board,
    :cpus,
    :node_count,
    :tasks,
    :partition,
    :prefer,
    :memory_per_cpu,
    :memory_per_node,
    :minimum_cpus_per_node,
    :minimum_tmp_disk_per_node,
    :power,
    :preempt_time,
    :preemptable_time,
    :pre_sus_time,
    :hold,
    :priority,
    :profile,
    :qos,
    :reboot,
    :required_nodes,
    :minimum_switches,
    :requeue,
    :resize_time,
    :restart_cnt,
    :resv_name,
    :scheduled_nodes,
    :selinux_context,
    :shared,
    :exclusive,
    :oversubscribe,
    :show_flags,
    :sockets_per_board,
    :sockets_per_node,
    :start_time,
    :state_description,
    :state_reason,
    :standard_error,
    :standard_input,
    :standard_output,
    :submit_time,
    :suspend_time,
    :system_comment,
    :time_limit,
    :time_minimum,
    :threads_per_core,
    :tres_bind,
    :tres_freq,
    :tres_per_job,
    :tres_per_node,
    :tres_per_socket,
    :tres_per_task,
    :tres_req_str,
    :tres_alloc_str,
    :user_id,
    :user_name,
    :maximum_switch_wait_time,
    :wckey,
    :current_working_directory
  ]

  @type t :: %__MODULE__{
    :account => String.t | nil,
    :accrue_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :admin_comment => String.t | nil,
    :allocating_node => String.t | nil,
    :array_job_id => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :array_task_id => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :array_max_tasks => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :array_task_string => String.t | nil,
    :association_id => integer() | nil,
    :batch_features => String.t | nil,
    :batch_flag => boolean() | nil,
    :batch_host => String.t | nil,
    :flags => [String.t] | nil,
    :burst_buffer => String.t | nil,
    :burst_buffer_state => String.t | nil,
    :cluster => String.t | nil,
    :cluster_features => String.t | nil,
    :command => String.t | nil,
    :comment => String.t | nil,
    :container => String.t | nil,
    :container_id => String.t | nil,
    :contiguous => boolean() | nil,
    :core_spec => integer() | nil,
    :thread_spec => integer() | nil,
    :cores_per_socket => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :billable_tres => SlurmRESTAPI.Model.V0040Float64NoVal.t | nil,
    :cpus_per_task => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :cpu_frequency_minimum => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :cpu_frequency_maximum => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :cpu_frequency_governor => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :cpus_per_tres => String.t | nil,
    :cron => String.t | nil,
    :deadline => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :delay_boot => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :dependency => String.t | nil,
    :derived_exit_code => SlurmRESTAPI.Model.V0040ProcessExitCodeVerbose.t | nil,
    :eligible_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :end_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :excluded_nodes => String.t | nil,
    :exit_code => SlurmRESTAPI.Model.V0040ProcessExitCodeVerbose.t | nil,
    :extra => String.t | nil,
    :failed_node => String.t | nil,
    :features => String.t | nil,
    :federation_origin => String.t | nil,
    :federation_siblings_active => String.t | nil,
    :federation_siblings_viable => String.t | nil,
    :gres_detail => [String.t] | nil,
    :group_id => integer() | nil,
    :group_name => String.t | nil,
    :het_job_id => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :het_job_id_set => String.t | nil,
    :het_job_offset => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :job_id => integer() | nil,
    :job_resources => SlurmRESTAPI.Model.V0040JobRes.t | nil,
    :job_size_str => [String.t] | nil,
    :job_state => [String.t] | nil,
    :last_sched_evaluation => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :licenses => String.t | nil,
    :mail_type => [String.t] | nil,
    :mail_user => String.t | nil,
    :max_cpus => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :max_nodes => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :mcs_label => String.t | nil,
    :memory_per_tres => String.t | nil,
    :name => String.t | nil,
    :network => String.t | nil,
    :nodes => String.t | nil,
    :nice => integer() | nil,
    :tasks_per_core => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :tasks_per_tres => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :tasks_per_node => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :tasks_per_socket => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :tasks_per_board => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :cpus => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :node_count => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :tasks => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :partition => String.t | nil,
    :prefer => String.t | nil,
    :memory_per_cpu => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :memory_per_node => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :minimum_cpus_per_node => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :minimum_tmp_disk_per_node => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :power => SlurmRESTAPI.Model.V0040JobInfoPower.t | nil,
    :preempt_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :preemptable_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :pre_sus_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :hold => boolean() | nil,
    :priority => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :profile => [String.t] | nil,
    :qos => String.t | nil,
    :reboot => boolean() | nil,
    :required_nodes => String.t | nil,
    :minimum_switches => integer() | nil,
    :requeue => boolean() | nil,
    :resize_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :restart_cnt => integer() | nil,
    :resv_name => String.t | nil,
    :scheduled_nodes => String.t | nil,
    :selinux_context => String.t | nil,
    :shared => [String.t] | nil,
    :exclusive => [String.t] | nil,
    :oversubscribe => boolean() | nil,
    :show_flags => [String.t] | nil,
    :sockets_per_board => integer() | nil,
    :sockets_per_node => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :start_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :state_description => String.t | nil,
    :state_reason => String.t | nil,
    :standard_error => String.t | nil,
    :standard_input => String.t | nil,
    :standard_output => String.t | nil,
    :submit_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :suspend_time => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :system_comment => String.t | nil,
    :time_limit => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :time_minimum => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :threads_per_core => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil,
    :tres_bind => String.t | nil,
    :tres_freq => String.t | nil,
    :tres_per_job => String.t | nil,
    :tres_per_node => String.t | nil,
    :tres_per_socket => String.t | nil,
    :tres_per_task => String.t | nil,
    :tres_req_str => String.t | nil,
    :tres_alloc_str => String.t | nil,
    :user_id => integer() | nil,
    :user_name => String.t | nil,
    :maximum_switch_wait_time => integer() | nil,
    :wckey => String.t | nil,
    :current_working_directory => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:accrue_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:array_job_id, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:array_task_id, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:array_max_tasks, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:cores_per_socket, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:billable_tres, :struct, SlurmRESTAPI.Model.V0040Float64NoVal)
     |> Deserializer.deserialize(:cpus_per_task, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:cpu_frequency_minimum, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:cpu_frequency_maximum, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:cpu_frequency_governor, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:deadline, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:delay_boot, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:derived_exit_code, :struct, SlurmRESTAPI.Model.V0040ProcessExitCodeVerbose)
     |> Deserializer.deserialize(:eligible_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:end_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:exit_code, :struct, SlurmRESTAPI.Model.V0040ProcessExitCodeVerbose)
     |> Deserializer.deserialize(:het_job_id, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:het_job_offset, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:job_resources, :struct, SlurmRESTAPI.Model.V0040JobRes)
     |> Deserializer.deserialize(:last_sched_evaluation, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:max_cpus, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:max_nodes, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:tasks_per_core, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:tasks_per_tres, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:tasks_per_node, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:tasks_per_socket, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:tasks_per_board, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:cpus, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:node_count, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:tasks, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:memory_per_cpu, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:memory_per_node, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:minimum_cpus_per_node, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:minimum_tmp_disk_per_node, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:power, :struct, SlurmRESTAPI.Model.V0040JobInfoPower)
     |> Deserializer.deserialize(:preempt_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:preemptable_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:pre_sus_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:priority, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:resize_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:sockets_per_node, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
     |> Deserializer.deserialize(:start_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:submit_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:suspend_time, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:time_limit, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:time_minimum, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:threads_per_core, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
  end
end

