# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040PartitionInfoMaximums do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :cpus_per_node,
    :cpus_per_socket,
    :memory_per_cpu,
    :partition_memory_per_cpu,
    :partition_memory_per_node,
    :nodes,
    :shares,
    :oversubscribe,
    :time,
    :over_time_limit
  ]

  @type t :: %__MODULE__{
    :cpus_per_node => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :cpus_per_socket => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :memory_per_cpu => integer() | nil,
    :partition_memory_per_cpu => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :partition_memory_per_node => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :nodes => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :shares => integer() | nil,
    :oversubscribe => SlurmRESTAPI.Model.V0040PartitionInfoMaximumsOversubscribe.t | nil,
    :time => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :over_time_limit => SlurmRESTAPI.Model.V0040Uint16NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cpus_per_node, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:cpus_per_socket, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:partition_memory_per_cpu, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:partition_memory_per_node, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:nodes, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:oversubscribe, :struct, SlurmRESTAPI.Model.V0040PartitionInfoMaximumsOversubscribe)
     |> Deserializer.deserialize(:time, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:over_time_limit, :struct, SlurmRESTAPI.Model.V0040Uint16NoVal)
  end
end

