# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040OpenapiSlurmdbdConfigResp do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :clusters,
    :tres,
    :accounts,
    :users,
    :qos,
    :wckeys,
    :associations,
    :instances,
    :meta,
    :errors,
    :warnings
  ]

  @type t :: %__MODULE__{
    :clusters => [SlurmRESTAPI.Model.V0040ClusterRec.t] | nil,
    :tres => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :accounts => [SlurmRESTAPI.Model.V0040Account.t] | nil,
    :users => [SlurmRESTAPI.Model.V0040User.t] | nil,
    :qos => [SlurmRESTAPI.Model.V0040Qos.t] | nil,
    :wckeys => [SlurmRESTAPI.Model.V0040Wckey.t] | nil,
    :associations => [SlurmRESTAPI.Model.V0040Assoc.t] | nil,
    :instances => [SlurmRESTAPI.Model.V0040Instance.t] | nil,
    :meta => SlurmRESTAPI.Model.V0040OpenapiMeta.t | nil,
    :errors => [SlurmRESTAPI.Model.V0040OpenapiError.t] | nil,
    :warnings => [SlurmRESTAPI.Model.V0040OpenapiWarning.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:clusters, :list, SlurmRESTAPI.Model.V0040ClusterRec)
     |> Deserializer.deserialize(:tres, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:accounts, :list, SlurmRESTAPI.Model.V0040Account)
     |> Deserializer.deserialize(:users, :list, SlurmRESTAPI.Model.V0040User)
     |> Deserializer.deserialize(:qos, :list, SlurmRESTAPI.Model.V0040Qos)
     |> Deserializer.deserialize(:wckeys, :list, SlurmRESTAPI.Model.V0040Wckey)
     |> Deserializer.deserialize(:associations, :list, SlurmRESTAPI.Model.V0040Assoc)
     |> Deserializer.deserialize(:instances, :list, SlurmRESTAPI.Model.V0040Instance)
     |> Deserializer.deserialize(:meta, :struct, SlurmRESTAPI.Model.V0040OpenapiMeta)
     |> Deserializer.deserialize(:errors, :list, SlurmRESTAPI.Model.V0040OpenapiError)
     |> Deserializer.deserialize(:warnings, :list, SlurmRESTAPI.Model.V0040OpenapiWarning)
  end
end

