# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040SharesUint64Tres do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :value
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :value => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:value, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
  end
end

