# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039PartitionInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :nodes,
    :accounts,
    :groups,
    :qos,
    :alternate,
    :tres,
    :cluster,
    :cpus,
    :defaults,
    :grace_time,
    :maximums,
    :minimums,
    :name,
    :node_sets,
    :priority,
    :timeouts,
    :suspend_time
  ]

  @type t :: %__MODULE__{
    :nodes => SlurmRESTAPI.Model.V0039PartitionInfoNodes.t | nil,
    :accounts => SlurmRESTAPI.Model.V0039PartitionInfoAccounts.t | nil,
    :groups => SlurmRESTAPI.Model.V0039PartitionInfoGroups.t | nil,
    :qos => SlurmRESTAPI.Model.V0039PartitionInfoQos.t | nil,
    :alternate => String.t | nil,
    :tres => SlurmRESTAPI.Model.V0039PartitionInfoTres.t | nil,
    :cluster => String.t | nil,
    :cpus => SlurmRESTAPI.Model.V0039PartitionInfoCpus.t | nil,
    :defaults => SlurmRESTAPI.Model.V0039PartitionInfoDefaults.t | nil,
    :grace_time => integer() | nil,
    :maximums => SlurmRESTAPI.Model.V0039PartitionInfoMaximums.t | nil,
    :minimums => SlurmRESTAPI.Model.V0039PartitionInfoMinimums.t | nil,
    :name => String.t | nil,
    :node_sets => String.t | nil,
    :priority => SlurmRESTAPI.Model.V0039PartitionInfoPriority.t | nil,
    :timeouts => SlurmRESTAPI.Model.V0039PartitionInfoTimeouts.t | nil,
    :suspend_time => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:nodes, :struct, SlurmRESTAPI.Model.V0039PartitionInfoNodes)
     |> Deserializer.deserialize(:accounts, :struct, SlurmRESTAPI.Model.V0039PartitionInfoAccounts)
     |> Deserializer.deserialize(:groups, :struct, SlurmRESTAPI.Model.V0039PartitionInfoGroups)
     |> Deserializer.deserialize(:qos, :struct, SlurmRESTAPI.Model.V0039PartitionInfoQos)
     |> Deserializer.deserialize(:tres, :struct, SlurmRESTAPI.Model.V0039PartitionInfoTres)
     |> Deserializer.deserialize(:cpus, :struct, SlurmRESTAPI.Model.V0039PartitionInfoCpus)
     |> Deserializer.deserialize(:defaults, :struct, SlurmRESTAPI.Model.V0039PartitionInfoDefaults)
     |> Deserializer.deserialize(:maximums, :struct, SlurmRESTAPI.Model.V0039PartitionInfoMaximums)
     |> Deserializer.deserialize(:minimums, :struct, SlurmRESTAPI.Model.V0039PartitionInfoMinimums)
     |> Deserializer.deserialize(:priority, :struct, SlurmRESTAPI.Model.V0039PartitionInfoPriority)
     |> Deserializer.deserialize(:timeouts, :struct, SlurmRESTAPI.Model.V0039PartitionInfoTimeouts)
     |> Deserializer.deserialize(:suspend_time, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
  end
end

