# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespInstancesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :cluster,
    :extra,
    :instance_id,
    :instance_type,
    :node_name,
    :time
  ]

  @type t :: %__MODULE__{
    :cluster => String.t | nil,
    :extra => String.t | nil,
    :instance_id => String.t | nil,
    :instance_type => String.t | nil,
    :node_name => String.t | nil,
    :time => SlurmRESTAPI.Model.V0040InstanceTime.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:time, :struct, SlurmRESTAPI.Model.V0040InstanceTime)
  end
end

