# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039License do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :LicenseName,
    :Total,
    :Used,
    :Free,
    :Remote,
    :Reserved,
    :LastConsumed,
    :LastDeficit,
    :LastUpdate
  ]

  @type t :: %__MODULE__{
    :LicenseName => String.t | nil,
    :Total => integer() | nil,
    :Used => integer() | nil,
    :Free => integer() | nil,
    :Remote => boolean() | nil,
    :Reserved => integer() | nil,
    :LastConsumed => integer() | nil,
    :LastDeficit => integer() | nil,
    :LastUpdate => integer() | nil
  }

  def decode(value) do
    value
  end
end

