# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourly do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :last_run,
    :duration
  ]

  @type t :: %__MODULE__{
    :count => integer() | nil,
    :last_run => integer() | nil,
    :duration => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourlyDuration.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:duration, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsRollupsHourlyDuration)
  end
end

