# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040JobMcs do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :label
  ]

  @type t :: %__MODULE__{
    :label => String.t | nil
  }

  def decode(value) do
    value
  end
end

