# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPer do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :accruing,
    :submitted,
    :wall_clock
  ]

  @type t :: %__MODULE__{
    :count => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobsCount.t | nil,
    :accruing => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobsAccruing.t | nil,
    :submitted => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPerSubmitted.t | nil,
    :wall_clock => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxWallClockPerJob.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:count, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobsCount)
     |> Deserializer.deserialize(:accruing, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobsAccruing)
     |> Deserializer.deserialize(:submitted, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxJobsPerSubmitted)
     |> Deserializer.deserialize(:wall_clock, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxWallClockPerJob)
  end
end

