# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039AssocMaxTres do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :total,
    :minutes,
    :group,
    :per
  ]

  @type t :: %__MODULE__{
    :total => [SlurmRESTAPI.Model.V0039Tres.t] | nil,
    :minutes => SlurmRESTAPI.Model.V0039AssocMaxTresMinutes.t | nil,
    :group => SlurmRESTAPI.Model.V0039AssocMaxTresGroup.t | nil,
    :per => SlurmRESTAPI.Model.V0039AssocMaxTresPer.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:total, :list, SlurmRESTAPI.Model.V0039Tres)
     |> Deserializer.deserialize(:minutes, :struct, SlurmRESTAPI.Model.V0039AssocMaxTresMinutes)
     |> Deserializer.deserialize(:group, :struct, SlurmRESTAPI.Model.V0039AssocMaxTresGroup)
     |> Deserializer.deserialize(:per, :struct, SlurmRESTAPI.Model.V0039AssocMaxTresPer)
  end
end

