# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039StepTresRequested do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :max,
    :min,
    :average,
    :total
  ]

  @type t :: %__MODULE__{
    :max => [SlurmRESTAPI.Model.V0039Tres.t] | nil,
    :min => [SlurmRESTAPI.Model.V0039Tres.t] | nil,
    :average => [SlurmRESTAPI.Model.V0039Tres.t] | nil,
    :total => [SlurmRESTAPI.Model.V0039Tres.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:max, :list, SlurmRESTAPI.Model.V0039Tres)
     |> Deserializer.deserialize(:min, :list, SlurmRESTAPI.Model.V0039Tres)
     |> Deserializer.deserialize(:average, :list, SlurmRESTAPI.Model.V0039Tres)
     |> Deserializer.deserialize(:total, :list, SlurmRESTAPI.Model.V0039Tres)
  end
end

