# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTres do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :total,
    :group,
    :minutes,
    :per
  ]

  @type t :: %__MODULE__{
    :total => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :group => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresGroup.t | nil,
    :minutes => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresMinutes.t | nil,
    :per => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresPer.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:total, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:group, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresGroup)
     |> Deserializer.deserialize(:minutes, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresMinutes)
     |> Deserializer.deserialize(:per, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMaxTresPer)
  end
end

