# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :select_type,
    :list,
    :whole,
    :allocation
  ]

  @type t :: %__MODULE__{
    :count => integer() | nil,
    :select_type => [String.t] | nil,
    :list => String.t | nil,
    :whole => boolean() | nil,
    :allocation => [SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInner.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:allocation, :list, SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInner)
  end
end

