# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039AssocUsage do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :accrue_job_count,
    :group_used_wallclock,
    :fairshare_factor,
    :fairshare_shares,
    :normalized_priority,
    :normalized_shares,
    :effective_normalized_usage,
    :normalized_usage,
    :raw_usage,
    :active_jobs,
    :job_count,
    :fairshare_level
  ]

  @type t :: %__MODULE__{
    :accrue_job_count => integer() | nil,
    :group_used_wallclock => float() | nil,
    :fairshare_factor => float() | nil,
    :fairshare_shares => integer() | nil,
    :normalized_priority => float() | nil,
    :normalized_shares => float() | nil,
    :effective_normalized_usage => float() | nil,
    :normalized_usage => float() | nil,
    :raw_usage => float() | nil,
    :active_jobs => integer() | nil,
    :job_count => integer() | nil,
    :fairshare_level => float() | nil
  }

  def decode(value) do
    value
  end
end

