# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040JobRequired do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :CPUs,
    :memory_per_cpu,
    :memory_per_node
  ]

  @type t :: %__MODULE__{
    :CPUs => integer() | nil,
    :memory_per_cpu => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil,
    :memory_per_node => SlurmRESTAPI.Model.V0040Uint64NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:memory_per_cpu, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
     |> Deserializer.deserialize(:memory_per_node, :struct, SlurmRESTAPI.Model.V0040Uint64NoVal)
  end
end

