# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039Node do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :architecture,
    :burstbuffer_network_address,
    :boards,
    :boot_time,
    :cluster_name,
    :cores,
    :specialized_cores,
    :cpu_binding,
    :cpu_load,
    :free_mem,
    :cpus,
    :effective_cpus,
    :specialized_cpus,
    :energy,
    :external_sensors,
    :extra,
    :power,
    :features,
    :active_features,
    :gres,
    :gres_drained,
    :gres_used,
    :last_busy,
    :mcs_label,
    :specialized_memory,
    :name,
    :next_state_after_reboot,
    :address,
    :hostname,
    :state,
    :operating_system,
    :owner,
    :partitions,
    :port,
    :real_memory,
    :comment,
    :reason,
    :reason_changed_at,
    :reason_set_by_user,
    :resume_after,
    :reservation,
    :alloc_memory,
    :alloc_cpus,
    :alloc_idle_cpus,
    :tres_used,
    :tres_weighted,
    :slurmd_start_time,
    :sockets,
    :threads,
    :temporary_disk,
    :weight,
    :tres,
    :version
  ]

  @type t :: %__MODULE__{
    :architecture => String.t | nil,
    :burstbuffer_network_address => String.t | nil,
    :boards => integer() | nil,
    :boot_time => integer() | nil,
    :cluster_name => String.t | nil,
    :cores => integer() | nil,
    :specialized_cores => integer() | nil,
    :cpu_binding => integer() | nil,
    :cpu_load => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil,
    :free_mem => SlurmRESTAPI.Model.V0039Uint64NoVal.t | nil,
    :cpus => integer() | nil,
    :effective_cpus => integer() | nil,
    :specialized_cpus => String.t | nil,
    :energy => SlurmRESTAPI.Model.V0039AcctGatherEnergy.t | nil,
    :external_sensors => map() | nil,
    :extra => String.t | nil,
    :power => map() | nil,
    :features => [String.t] | nil,
    :active_features => [String.t] | nil,
    :gres => String.t | nil,
    :gres_drained => String.t | nil,
    :gres_used => String.t | nil,
    :last_busy => integer() | nil,
    :mcs_label => String.t | nil,
    :specialized_memory => integer() | nil,
    :name => String.t | nil,
    :next_state_after_reboot => [String.t] | nil,
    :address => String.t | nil,
    :hostname => String.t | nil,
    :state => [String.t] | nil,
    :operating_system => String.t | nil,
    :owner => String.t | nil,
    :partitions => [String.t] | nil,
    :port => integer() | nil,
    :real_memory => integer() | nil,
    :comment => String.t | nil,
    :reason => String.t | nil,
    :reason_changed_at => integer() | nil,
    :reason_set_by_user => String.t | nil,
    :resume_after => SlurmRESTAPI.Model.V0039Uint64NoVal.t | nil,
    :reservation => String.t | nil,
    :alloc_memory => integer() | nil,
    :alloc_cpus => integer() | nil,
    :alloc_idle_cpus => integer() | nil,
    :tres_used => String.t | nil,
    :tres_weighted => float() | nil,
    :slurmd_start_time => integer() | nil,
    :sockets => integer() | nil,
    :threads => integer() | nil,
    :temporary_disk => integer() | nil,
    :weight => integer() | nil,
    :tres => String.t | nil,
    :version => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cpu_load, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
     |> Deserializer.deserialize(:free_mem, :struct, SlurmRESTAPI.Model.V0039Uint64NoVal)
     |> Deserializer.deserialize(:energy, :struct, SlurmRESTAPI.Model.V0039AcctGatherEnergy)
     |> Deserializer.deserialize(:resume_after, :struct, SlurmRESTAPI.Model.V0039Uint64NoVal)
  end
end

