# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiDiagRespStatisticsPendingRpcsInner do
  @moduledoc """
  Pending RPCs
  """

  @derive Jason.Encoder
  defstruct [
    :type_id,
    :message_type,
    :count
  ]

  @type t :: %__MODULE__{
    :type_id => integer(),
    :message_type => String.t,
    :count => integer()
  }

  def decode(value) do
    value
  end
end

