# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerCpus do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :used
  ]

  @type t :: %__MODULE__{
    :count => integer() | nil,
    :used => integer() | nil
  }

  def decode(value) do
    value
  end
end

