# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiDiagRespStatisticsScheduleExit do
  @moduledoc """
  Reasons for which the scheduling cycle exited since last reset
  """

  @derive Jason.Encoder
  defstruct [
    :end_job_queue,
    :default_queue_depth,
    :max_job_start,
    :max_rpc_cnt,
    :max_sched_time,
    :licenses
  ]

  @type t :: %__MODULE__{
    :end_job_queue => integer() | nil,
    :default_queue_depth => integer() | nil,
    :max_job_start => integer() | nil,
    :max_rpc_cnt => integer() | nil,
    :max_sched_time => integer() | nil,
    :licenses => integer() | nil
  }

  def decode(value) do
    value
  end
end

