# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobs do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :accruing,
    :count
  ]

  @type t :: %__MODULE__{
    :accruing => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobsAccruing.t | nil,
    :count => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobsCount.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:accruing, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobsAccruing)
     |> Deserializer.deserialize(:count, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespQosInnerLimitsMaxActiveJobsCount)
  end
end

