# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039Error do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :error_number,
    :error,
    :source,
    :description
  ]

  @type t :: %__MODULE__{
    :error_number => integer() | nil,
    :error => String.t | nil,
    :source => String.t | nil,
    :description => String.t | nil
  }

  def decode(value) do
    value
  end
end

