# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerTime do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :elapsed,
    :eligible,
    :end,
    :planned,
    :start,
    :submission,
    :suspended,
    :system,
    :limit,
    :total,
    :user
  ]

  @type t :: %__MODULE__{
    :elapsed => integer() | nil,
    :eligible => integer() | nil,
    :end => integer() | nil,
    :planned => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerTimePlanned.t | nil,
    :start => integer() | nil,
    :submission => integer() | nil,
    :suspended => integer() | nil,
    :system => SlurmRESTAPI.Model.V0040JobTimeSystem.t | nil,
    :limit => SlurmRESTAPI.Model.V0041JobDescMsgTimeLimit.t | nil,
    :total => SlurmRESTAPI.Model.V0040JobTimeTotal.t | nil,
    :user => SlurmRESTAPI.Model.V0040JobTimeUser.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:planned, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerTimePlanned)
     |> Deserializer.deserialize(:system, :struct, SlurmRESTAPI.Model.V0040JobTimeSystem)
     |> Deserializer.deserialize(:limit, :struct, SlurmRESTAPI.Model.V0041JobDescMsgTimeLimit)
     |> Deserializer.deserialize(:total, :struct, SlurmRESTAPI.Model.V0040JobTimeTotal)
     |> Deserializer.deserialize(:user, :struct, SlurmRESTAPI.Model.V0040JobTimeUser)
  end
end

