# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaults do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :memory_per_cpu,
    :partition_memory_per_cpu,
    :partition_memory_per_node,
    :time,
    :job
  ]

  @type t :: %__MODULE__{
    :memory_per_cpu => integer() | nil,
    :partition_memory_per_cpu => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerCpu.t | nil,
    :partition_memory_per_node => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerNode.t | nil,
    :time => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaultsTime.t | nil,
    :job => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:partition_memory_per_cpu, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerCpu)
     |> Deserializer.deserialize(:partition_memory_per_node, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaultsPartitionMemoryPerNode)
     |> Deserializer.deserialize(:time, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerDefaultsTime)
  end
end

