# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040UserShort do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :adminlevel,
    :defaultaccount,
    :defaultwckey
  ]

  @type t :: %__MODULE__{
    :adminlevel => [String.t] | nil,
    :defaultaccount => String.t | nil,
    :defaultwckey => String.t | nil
  }

  def decode(value) do
    value
  end
end

