# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039ClusterRecController do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :host,
    :port
  ]

  @type t :: %__MODULE__{
    :host => String.t | nil,
    :port => integer() | nil
  }

  def decode(value) do
    value
  end
end

