# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAccountsInnerAssociationsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account,
    :cluster,
    :partition,
    :user,
    :id
  ]

  @type t :: %__MODULE__{
    :account => String.t | nil,
    :cluster => String.t | nil,
    :partition => String.t | nil,
    :user => String.t,
    :id => integer() | nil
  }

  def decode(value) do
    value
  end
end

