# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041KillJobsMsg do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account,
    :flags,
    :job_name,
    :jobs,
    :partition,
    :qos,
    :reservation,
    :signal,
    :job_state,
    :user_id,
    :user_name,
    :wckey,
    :nodes
  ]

  @type t :: %__MODULE__{
    :account => String.t | nil,
    :flags => [String.t] | nil,
    :job_name => String.t | nil,
    :jobs => [String.t] | nil,
    :partition => String.t | nil,
    :qos => String.t | nil,
    :reservation => String.t | nil,
    :signal => String.t | nil,
    :job_state => [String.t] | nil,
    :user_id => String.t | nil,
    :user_name => String.t | nil,
    :wckey => String.t | nil,
    :nodes => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

