# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039PartitionInfoTres do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :billing_weights,
    :configured
  ]

  @type t :: %__MODULE__{
    :billing_weights => String.t | nil,
    :configured => String.t | nil
  }

  def decode(value) do
    value
  end
end

