# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040ProcessExitCodeVerbose do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :return_code,
    :signal
  ]

  @type t :: %__MODULE__{
    :status => [String.t] | nil,
    :return_code => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :signal => SlurmRESTAPI.Model.V0040ProcessExitCodeVerboseSignal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:return_code, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:signal, :struct, SlurmRESTAPI.Model.V0040ProcessExitCodeVerboseSignal)
  end
end

