# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040InstanceTime do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :time_end,
    :time_start
  ]

  @type t :: %__MODULE__{
    :time_end => integer() | nil,
    :time_start => integer() | nil
  }

  def decode(value) do
    value
  end
end

