# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039PartitionInfoTimeouts do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :resume,
    :suspend
  ]

  @type t :: %__MODULE__{
    :resume => SlurmRESTAPI.Model.V0039Uint16NoVal.t | nil,
    :suspend => SlurmRESTAPI.Model.V0039Uint16NoVal.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:resume, :struct, SlurmRESTAPI.Model.V0039Uint16NoVal)
     |> Deserializer.deserialize(:suspend, :struct, SlurmRESTAPI.Model.V0039Uint16NoVal)
  end
end

