# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :time,
    :exit_code,
    :nodes,
    :tasks,
    :pid,
    :CPU,
    :kill_request_user,
    :state,
    :statistics,
    :step,
    :task,
    :tres
  ]

  @type t :: %__MODULE__{
    :time => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime.t | nil,
    :exit_code => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerExitCode.t | nil,
    :nodes => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerNodes.t | nil,
    :tasks => SlurmRESTAPI.Model.V0040StepTasks.t | nil,
    :pid => String.t | nil,
    :CPU => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCpu.t | nil,
    :kill_request_user => String.t | nil,
    :state => [String.t] | nil,
    :statistics => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatistics.t | nil,
    :step => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStep.t | nil,
    :task => SlurmRESTAPI.Model.V0040StepTask.t | nil,
    :tres => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTres.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:time, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTime)
     |> Deserializer.deserialize(:exit_code, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerExitCode)
     |> Deserializer.deserialize(:nodes, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerNodes)
     |> Deserializer.deserialize(:tasks, :struct, SlurmRESTAPI.Model.V0040StepTasks)
     |> Deserializer.deserialize(:CPU, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerCpu)
     |> Deserializer.deserialize(:statistics, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStatistics)
     |> Deserializer.deserialize(:step, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerStep)
     |> Deserializer.deserialize(:task, :struct, SlurmRESTAPI.Model.V0040StepTask)
     |> Deserializer.deserialize(:tres, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTres)
  end
end

