# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039Assoc do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account,
    :cluster,
    :default,
    :flags,
    :max,
    :is_default,
    :min,
    :parent_account,
    :partition,
    :priority,
    :qos,
    :shares_raw,
    :usage,
    :user
  ]

  @type t :: %__MODULE__{
    :account => String.t | nil,
    :cluster => String.t | nil,
    :default => SlurmRESTAPI.Model.V0039AssocDefault.t | nil,
    :flags => [String.t] | nil,
    :max => SlurmRESTAPI.Model.V0039AssocMax.t | nil,
    :is_default => boolean() | nil,
    :min => SlurmRESTAPI.Model.V0039AssocMin.t | nil,
    :parent_account => String.t | nil,
    :partition => String.t | nil,
    :priority => SlurmRESTAPI.Model.V0039Uint32NoVal.t | nil,
    :qos => [String.t] | nil,
    :shares_raw => integer() | nil,
    :usage => SlurmRESTAPI.Model.V0039AssocUsage.t | nil,
    :user => String.t
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:default, :struct, SlurmRESTAPI.Model.V0039AssocDefault)
     |> Deserializer.deserialize(:max, :struct, SlurmRESTAPI.Model.V0039AssocMax)
     |> Deserializer.deserialize(:min, :struct, SlurmRESTAPI.Model.V0039AssocMin)
     |> Deserializer.deserialize(:priority, :struct, SlurmRESTAPI.Model.V0039Uint32NoVal)
     |> Deserializer.deserialize(:usage, :struct, SlurmRESTAPI.Model.V0039AssocUsage)
  end
end

