# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040StepNodes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :range,
    :list
  ]

  @type t :: %__MODULE__{
    :count => integer() | nil,
    :range => String.t | nil,
    :list => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

