# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039Accounting do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :allocated,
    :id,
    :start,
    :TRES
  ]

  @type t :: %__MODULE__{
    :allocated => SlurmRESTAPI.Model.V0039AccountingAllocated.t | nil,
    :id => integer() | nil,
    :start => integer() | nil,
    :TRES => SlurmRESTAPI.Model.V0039Tres.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:allocated, :struct, SlurmRESTAPI.Model.V0039AccountingAllocated)
     |> Deserializer.deserialize(:TRES, :struct, SlurmRESTAPI.Model.V0039Tres)
  end
end

