# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSharesRespShares do
  @moduledoc """
  fairshare info
  """

  @derive Jason.Encoder
  defstruct [
    :shares,
    :total_shares
  ]

  @type t :: %__MODULE__{
    :shares => [SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInner.t] | nil,
    :total_shares => integer() | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:shares, :list, SlurmRESTAPI.Model.V0041OpenapiSharesRespSharesSharesInner)
  end
end

