# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040AssocRecSet do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :comment,
    :defaultqos,
    :grpjobs,
    :grpjobsaccrue,
    :grpsubmitjobs,
    :grptres,
    :grptresmins,
    :grptresrunmins,
    :grpwall,
    :maxjobs,
    :maxjobsaccrue,
    :maxsubmitjobs,
    :maxtresminsperjob,
    :maxtresrunmins,
    :maxtresperjob,
    :maxtrespernode,
    :maxwalldurationperjob,
    :minpriothresh,
    :parent,
    :priority,
    :qoslevel,
    :fairshare
  ]

  @type t :: %__MODULE__{
    :comment => String.t | nil,
    :defaultqos => String.t | nil,
    :grpjobs => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :grpjobsaccrue => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :grpsubmitjobs => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :grptres => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :grptresmins => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :grptresrunmins => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :grpwall => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :maxjobs => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :maxjobsaccrue => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :maxsubmitjobs => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :maxtresminsperjob => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :maxtresrunmins => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :maxtresperjob => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :maxtrespernode => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :maxwalldurationperjob => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :minpriothresh => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :parent => String.t | nil,
    :priority => SlurmRESTAPI.Model.V0040Uint32NoVal.t | nil,
    :qoslevel => [String.t] | nil,
    :fairshare => integer() | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:grpjobs, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:grpjobsaccrue, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:grpsubmitjobs, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:grptres, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:grptresmins, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:grptresrunmins, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:grpwall, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:maxjobs, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:maxjobsaccrue, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:maxsubmitjobs, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:maxtresminsperjob, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:maxtresrunmins, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:maxtresperjob, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:maxtrespernode, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:maxwalldurationperjob, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:minpriothresh, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
     |> Deserializer.deserialize(:priority, :struct, SlurmRESTAPI.Model.V0040Uint32NoVal)
  end
end

