# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039JobSubmissionResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :meta,
    :errors,
    :warnings,
    :job_id,
    :step_id,
    :job_submit_user_msg
  ]

  @type t :: %__MODULE__{
    :meta => SlurmRESTAPI.Model.V0039Meta.t | nil,
    :errors => [SlurmRESTAPI.Model.V0039Error.t] | nil,
    :warnings => [SlurmRESTAPI.Model.V0039Warning.t] | nil,
    :job_id => integer() | nil,
    :step_id => String.t | nil,
    :job_submit_user_msg => String.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:meta, :struct, SlurmRESTAPI.Model.V0039Meta)
     |> Deserializer.deserialize(:errors, :list, SlurmRESTAPI.Model.V0039Error)
     |> Deserializer.deserialize(:warnings, :list, SlurmRESTAPI.Model.V0039Warning)
  end
end

