# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040Step do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :time,
    :exit_code,
    :nodes,
    :tasks,
    :pid,
    :CPU,
    :kill_request_user,
    :state,
    :statistics,
    :step,
    :task,
    :tres
  ]

  @type t :: %__MODULE__{
    :time => SlurmRESTAPI.Model.V0040StepTime.t | nil,
    :exit_code => SlurmRESTAPI.Model.V0040ProcessExitCodeVerbose.t | nil,
    :nodes => SlurmRESTAPI.Model.V0040StepNodes.t | nil,
    :tasks => SlurmRESTAPI.Model.V0040StepTasks.t | nil,
    :pid => String.t | nil,
    :CPU => SlurmRESTAPI.Model.V0040StepCpu.t | nil,
    :kill_request_user => String.t | nil,
    :state => [String.t] | nil,
    :statistics => SlurmRESTAPI.Model.V0040StepStatistics.t | nil,
    :step => SlurmRESTAPI.Model.V0040StepStep.t | nil,
    :task => SlurmRESTAPI.Model.V0040StepTask.t | nil,
    :tres => SlurmRESTAPI.Model.V0040StepTres.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:time, :struct, SlurmRESTAPI.Model.V0040StepTime)
     |> Deserializer.deserialize(:exit_code, :struct, SlurmRESTAPI.Model.V0040ProcessExitCodeVerbose)
     |> Deserializer.deserialize(:nodes, :struct, SlurmRESTAPI.Model.V0040StepNodes)
     |> Deserializer.deserialize(:tasks, :struct, SlurmRESTAPI.Model.V0040StepTasks)
     |> Deserializer.deserialize(:CPU, :struct, SlurmRESTAPI.Model.V0040StepCpu)
     |> Deserializer.deserialize(:statistics, :struct, SlurmRESTAPI.Model.V0040StepStatistics)
     |> Deserializer.deserialize(:step, :struct, SlurmRESTAPI.Model.V0040StepStep)
     |> Deserializer.deserialize(:task, :struct, SlurmRESTAPI.Model.V0040StepTask)
     |> Deserializer.deserialize(:tres, :struct, SlurmRESTAPI.Model.V0040StepTres)
  end
end

