# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040QosLimitsMax do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :active_jobs,
    :tres,
    :wall_clock,
    :jobs,
    :accruing
  ]

  @type t :: %__MODULE__{
    :active_jobs => SlurmRESTAPI.Model.V0040QosLimitsMaxActiveJobs.t | nil,
    :tres => SlurmRESTAPI.Model.V0040QosLimitsMaxTres.t | nil,
    :wall_clock => SlurmRESTAPI.Model.V0040QosLimitsMaxWallClock.t | nil,
    :jobs => SlurmRESTAPI.Model.V0040QosLimitsMaxJobs.t | nil,
    :accruing => SlurmRESTAPI.Model.V0040QosLimitsMaxJobsActiveJobs.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:active_jobs, :struct, SlurmRESTAPI.Model.V0040QosLimitsMaxActiveJobs)
     |> Deserializer.deserialize(:tres, :struct, SlurmRESTAPI.Model.V0040QosLimitsMaxTres)
     |> Deserializer.deserialize(:wall_clock, :struct, SlurmRESTAPI.Model.V0040QosLimitsMaxWallClock)
     |> Deserializer.deserialize(:jobs, :struct, SlurmRESTAPI.Model.V0040QosLimitsMaxJobs)
     |> Deserializer.deserialize(:accruing, :struct, SlurmRESTAPI.Model.V0040QosLimitsMaxJobsActiveJobs)
  end
end

