# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatistics do
  @moduledoc """
  statistics
  """

  @derive Jason.Encoder
  defstruct [
    :time_start,
    :rollups,
    :RPCs,
    :users
  ]

  @type t :: %__MODULE__{
    :time_start => integer() | nil,
    :rollups => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsRollups.t | nil,
    :RPCs => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsRpcsInner.t] | nil,
    :users => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsUsersInner.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rollups, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsRollups)
     |> Deserializer.deserialize(:RPCs, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsRpcsInner)
     |> Deserializer.deserialize(:users, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdStatsRespStatisticsUsersInner)
  end
end

