# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximums do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :cpus_per_node,
    :cpus_per_socket,
    :memory_per_cpu,
    :partition_memory_per_cpu,
    :partition_memory_per_node,
    :nodes,
    :shares,
    :oversubscribe,
    :time,
    :over_time_limit
  ]

  @type t :: %__MODULE__{
    :cpus_per_node => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerNode.t | nil,
    :cpus_per_socket => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerSocket.t | nil,
    :memory_per_cpu => integer() | nil,
    :partition_memory_per_cpu => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerCpu.t | nil,
    :partition_memory_per_node => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerNode.t | nil,
    :nodes => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsNodes.t | nil,
    :shares => integer() | nil,
    :oversubscribe => SlurmRESTAPI.Model.V0040PartitionInfoMaximumsOversubscribe.t | nil,
    :time => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsTime.t | nil,
    :over_time_limit => SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsOverTimeLimit.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cpus_per_node, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerNode)
     |> Deserializer.deserialize(:cpus_per_socket, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsCpusPerSocket)
     |> Deserializer.deserialize(:partition_memory_per_cpu, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerCpu)
     |> Deserializer.deserialize(:partition_memory_per_node, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsPartitionMemoryPerNode)
     |> Deserializer.deserialize(:nodes, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsNodes)
     |> Deserializer.deserialize(:oversubscribe, :struct, SlurmRESTAPI.Model.V0040PartitionInfoMaximumsOversubscribe)
     |> Deserializer.deserialize(:time, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsTime)
     |> Deserializer.deserialize(:over_time_limit, :struct, SlurmRESTAPI.Model.V0041OpenapiPartitionRespPartitionsInnerMaximumsOverTimeLimit)
  end
end

