# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040AssocMaxTres do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :total,
    :group,
    :minutes,
    :per
  ]

  @type t :: %__MODULE__{
    :total => [SlurmRESTAPI.Model.V0040Tres.t] | nil,
    :group => SlurmRESTAPI.Model.V0040AssocMaxTresGroup.t | nil,
    :minutes => SlurmRESTAPI.Model.V0040AssocMaxTresMinutes.t | nil,
    :per => SlurmRESTAPI.Model.V0040AssocMaxTresPer.t | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:total, :list, SlurmRESTAPI.Model.V0040Tres)
     |> Deserializer.deserialize(:group, :struct, SlurmRESTAPI.Model.V0040AssocMaxTresGroup)
     |> Deserializer.deserialize(:minutes, :struct, SlurmRESTAPI.Model.V0040AssocMaxTresMinutes)
     |> Deserializer.deserialize(:per, :struct, SlurmRESTAPI.Model.V0040AssocMaxTresPer)
  end
end

