# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInner do
  @moduledoc """
  RPCs by type
  """

  @derive Jason.Encoder
  defstruct [
    :type_id,
    :message_type,
    :count,
    :queued,
    :dropped,
    :cycle_last,
    :cycle_max,
    :total_time,
    :average_time
  ]

  @type t :: %__MODULE__{
    :type_id => integer(),
    :message_type => String.t,
    :count => integer(),
    :queued => integer(),
    :dropped => integer(),
    :cycle_last => integer(),
    :cycle_max => integer(),
    :total_time => integer(),
    :average_time => SlurmRESTAPI.Model.V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInnerAverageTime.t
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:average_time, :struct, SlurmRESTAPI.Model.V0041OpenapiDiagRespStatisticsRpcsByMessageTypeInnerAverageTime)
  end
end

