# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039PartitionInfoCpus do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :task_binding,
    :total
  ]

  @type t :: %__MODULE__{
    :task_binding => integer() | nil,
    :total => integer() | nil
  }

  def decode(value) do
    value
  end
end

