# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociation do
  @moduledoc """
  Association limits and options
  """

  @derive Jason.Encoder
  defstruct [
    :comment,
    :defaultqos,
    :grpjobs,
    :grpjobsaccrue,
    :grpsubmitjobs,
    :grptres,
    :grptresmins,
    :grptresrunmins,
    :grpwall,
    :maxjobs,
    :maxjobsaccrue,
    :maxsubmitjobs,
    :maxtresminsperjob,
    :maxtresrunmins,
    :maxtresperjob,
    :maxtrespernode,
    :maxwalldurationperjob,
    :minpriothresh,
    :parent,
    :priority,
    :qoslevel,
    :fairshare
  ]

  @type t :: %__MODULE__{
    :comment => String.t | nil,
    :defaultqos => String.t | nil,
    :grpjobs => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobs.t | nil,
    :grpjobsaccrue => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobsaccrue.t | nil,
    :grpsubmitjobs => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpsubmitjobs.t | nil,
    :grptres => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :grptresmins => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :grptresrunmins => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :grpwall => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpwall.t | nil,
    :maxjobs => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobs.t | nil,
    :maxjobsaccrue => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobsaccrue.t | nil,
    :maxsubmitjobs => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxsubmitjobs.t | nil,
    :maxtresminsperjob => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :maxtresrunmins => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :maxtresperjob => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :maxtrespernode => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner.t] | nil,
    :maxwalldurationperjob => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxwalldurationperjob.t | nil,
    :minpriothresh => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMinpriothresh.t | nil,
    :parent => String.t | nil,
    :priority => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerPriority.t | nil,
    :qoslevel => [String.t] | nil,
    :fairshare => integer() | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:grpjobs, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobs)
     |> Deserializer.deserialize(:grpjobsaccrue, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpjobsaccrue)
     |> Deserializer.deserialize(:grpsubmitjobs, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpsubmitjobs)
     |> Deserializer.deserialize(:grptres, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:grptresmins, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:grptresrunmins, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:grpwall, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationGrpwall)
     |> Deserializer.deserialize(:maxjobs, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobs)
     |> Deserializer.deserialize(:maxjobsaccrue, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxjobsaccrue)
     |> Deserializer.deserialize(:maxsubmitjobs, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxsubmitjobs)
     |> Deserializer.deserialize(:maxtresminsperjob, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:maxtresrunmins, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:maxtresperjob, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:maxtrespernode, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdJobsRespJobsInnerStepsInnerTresRequestedMaxInner)
     |> Deserializer.deserialize(:maxwalldurationperjob, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMaxwalldurationperjob)
     |> Deserializer.deserialize(:minpriothresh, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociationMinpriothresh)
     |> Deserializer.deserialize(:priority, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerPriority)
  end
end

