# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :accounting,
    :account,
    :cluster,
    :comment,
    :default,
    :flags,
    :max,
    :id,
    :is_default,
    :lineage,
    :min,
    :parent_account,
    :partition,
    :priority,
    :qos,
    :shares_raw,
    :user
  ]

  @type t :: %__MODULE__{
    :accounting => [SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInner.t] | nil,
    :account => String.t | nil,
    :cluster => String.t | nil,
    :comment => String.t | nil,
    :default => SlurmRESTAPI.Model.V0040AssocDefault.t | nil,
    :flags => [String.t] | nil,
    :max => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMax.t | nil,
    :id => integer() | nil,
    :is_default => boolean() | nil,
    :lineage => String.t | nil,
    :min => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMin.t | nil,
    :parent_account => String.t | nil,
    :partition => String.t | nil,
    :priority => SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerPriority.t | nil,
    :qos => [String.t] | nil,
    :shares_raw => integer() | nil,
    :user => String.t
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:accounting, :list, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespUsersInnerWckeysInnerAccountingInner)
     |> Deserializer.deserialize(:default, :struct, SlurmRESTAPI.Model.V0040AssocDefault)
     |> Deserializer.deserialize(:max, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMax)
     |> Deserializer.deserialize(:min, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerMin)
     |> Deserializer.deserialize(:priority, :struct, SlurmRESTAPI.Model.V0041OpenapiSlurmdbdConfigRespAssociationsInnerPriority)
  end
end

