# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :index,
    :cores
  ]

  @type t :: %__MODULE__{
    :index => integer(),
    :cores => [SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInnerCoresInner.t]
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:cores, :list, SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInnerCoresInner)
  end
end

