# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0040OpenapiJobPostResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :results,
    :job_id,
    :step_id,
    :job_submit_user_msg,
    :meta,
    :errors,
    :warnings
  ]

  @type t :: %__MODULE__{
    :results => [SlurmRESTAPI.Model.V0040JobArrayResponseMsgEntry.t] | nil,
    :job_id => String.t | nil,
    :step_id => String.t | nil,
    :job_submit_user_msg => String.t | nil,
    :meta => SlurmRESTAPI.Model.V0040OpenapiMeta.t | nil,
    :errors => [SlurmRESTAPI.Model.V0040OpenapiError.t] | nil,
    :warnings => [SlurmRESTAPI.Model.V0040OpenapiWarning.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:results, :list, SlurmRESTAPI.Model.V0040JobArrayResponseMsgEntry)
     |> Deserializer.deserialize(:meta, :struct, SlurmRESTAPI.Model.V0040OpenapiMeta)
     |> Deserializer.deserialize(:errors, :list, SlurmRESTAPI.Model.V0040OpenapiError)
     |> Deserializer.deserialize(:warnings, :list, SlurmRESTAPI.Model.V0040OpenapiWarning)
  end
end

