# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiJobInfoRespJobsInnerJobResourcesNodesAllocationInnerSocketsInnerCoresInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :index,
    :status
  ]

  @type t :: %__MODULE__{
    :index => integer(),
    :status => [String.t]
  }

  def decode(value) do
    value
  end
end

