# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0041OpenapiAccountsAddCondRespAssociationCondition do
  @moduledoc """
  CSV list of accounts, association limits and options, CSV list of clusters
  """

  @derive Jason.Encoder
  defstruct [
    :accounts,
    :association,
    :clusters
  ]

  @type t :: %__MODULE__{
    :accounts => [String.t],
    :association => SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociation.t | nil,
    :clusters => [String.t] | nil
  }

  alias SlurmRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:association, :struct, SlurmRESTAPI.Model.V0041OpenapiUsersAddCondRespAssociationConditionAssociation)
  end
end

