# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRESTAPI.Model.V0039JobInfoPower do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :flags
  ]

  @type t :: %__MODULE__{
    :flags => [any()] | nil
  }

  def decode(value) do
    value
  end
end

