# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038UpdateAccount do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts
  ]

  @type t :: %__MODULE__{
    :accounts => [SlurmRestAPI.Model.Dbv0038Account.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038UpdateAccount do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:accounts, :list, SlurmRestAPI.Model.Dbv0038Account, options)
  end
end

