# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038TresListInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :name,
    :id,
    :count
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :name => String.t | nil,
    :id => integer() | nil,
    :count => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038TresListInner do
  def decode(value, _options) do
    value
  end
end

