# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038AssociationMaxJobs do
  @moduledoc """
  Max jobs settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :per
  ]

  @type t :: %__MODULE__{
    :per => SlurmRestAPI.Model.Dbv0038AssociationMaxJobsPer.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038AssociationMaxJobs do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:per, :struct, SlurmRestAPI.Model.Dbv0038AssociationMaxJobsPer, options)
  end
end

