# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037QosLimitsMaxJobsActiveJobsPer do
  @moduledoc """
  Limits on active jobs per settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :account,
    :user
  ]

  @type t :: %__MODULE__{
    :account => integer() | nil,
    :user => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037QosLimitsMaxJobsActiveJobsPer do
  def decode(value, _options) do
    value
  end
end

