# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038JobTimeUser do
  @moduledoc """
  User land time values
  """

  @derive [Poison.Encoder]
  defstruct [
    :seconds,
    :microseconds
  ]

  @type t :: %__MODULE__{
    :seconds => integer() | nil,
    :microseconds => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038JobTimeUser do
  def decode(value, _options) do
    value
  end
end

