# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038DiagStatisticsRpcsInner do
  @moduledoc """
  Statistics by RPC type
  """

  @derive [Poison.Encoder]
  defstruct [
    :rpc,
    :count,
    :time
  ]

  @type t :: %__MODULE__{
    :rpc => String.t | nil,
    :count => integer() | nil,
    :time => SlurmRestAPI.Model.Dbv0038DiagStatisticsRpcsInnerTime.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038DiagStatisticsRpcsInner do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:time, :struct, SlurmRestAPI.Model.Dbv0038DiagStatisticsRpcsInnerTime, options)
  end
end

