# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038AssociationDefault do
  @moduledoc """
  Default settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :qos
  ]

  @type t :: %__MODULE__{
    :qos => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038AssociationDefault do
  def decode(value, _options) do
    value
  end
end

