# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037JobStepStatisticsCpu do
  @moduledoc """
  Statistics of CPU
  """

  @derive [Poison.Encoder]
  defstruct [
    :actual_frequency
  ]

  @type t :: %__MODULE__{
    :actual_frequency => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037JobStepStatisticsCpu do
  def decode(value, _options) do
    value
  end
end

