# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038QosLimitsMaxTresMinutesPer do
  @moduledoc """
  Max TRES minutes per settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :job,
    :account,
    :user,
    :qos
  ]

  @type t :: %__MODULE__{
    :job => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil,
    :account => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil,
    :user => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil,
    :qos => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038QosLimitsMaxTresMinutesPer do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:job, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
    |> deserialize(:account, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
    |> deserialize(:user, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
    |> deserialize(:qos, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
  end
end

