# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0039UpdateUsers do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :users
  ]

  @type t :: %__MODULE__{
    :users => [SlurmRestAPI.Model.V0039User.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0039UpdateUsers do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:users, :list, SlurmRestAPI.Model.V0039User, options)
  end
end

