# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0039TresInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :meta,
    :errors,
    :warnings,
    :tres
  ]

  @type t :: %__MODULE__{
    :meta => SlurmRestAPI.Model.Dbv0039Meta.t | nil,
    :errors => [SlurmRestAPI.Model.Dbv0039Error.t] | nil,
    :warnings => [SlurmRestAPI.Model.Dbv0039Warning.t] | nil,
    :tres => [SlurmRestAPI.Model.V0039Tres.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0039TresInfo do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:meta, :struct, SlurmRestAPI.Model.Dbv0039Meta, options)
    |> deserialize(:errors, :list, SlurmRestAPI.Model.Dbv0039Error, options)
    |> deserialize(:warnings, :list, SlurmRestAPI.Model.Dbv0039Warning, options)
    |> deserialize(:tres, :list, SlurmRestAPI.Model.V0039Tres, options)
  end
end

