# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038CoordinatorInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :direct
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :direct => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038CoordinatorInfo do
  def decode(value, _options) do
    value
  end
end

