# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038Wckey do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :cluster,
    :id,
    :name,
    :user,
    :flags,
    :accounting
  ]

  @type t :: %__MODULE__{
    :cluster => String.t | nil,
    :id => integer() | nil,
    :name => String.t | nil,
    :user => String.t | nil,
    :flags => [String.t] | nil,
    :accounting => [SlurmRestAPI.Model.Dbv0038Accounting.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038Wckey do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:accounting, :list, SlurmRestAPI.Model.Dbv0038Accounting, options)
  end
end

