# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037Wckey do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts,
    :cluster,
    :id,
    :name,
    :user,
    :flags
  ]

  @type t :: %__MODULE__{
    :accounts => [String.t] | nil,
    :cluster => String.t | nil,
    :id => integer() | nil,
    :name => String.t | nil,
    :user => String.t | nil,
    :flags => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037Wckey do
  def decode(value, _options) do
    value
  end
end

