# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038QosLimits do
  @moduledoc """
  Assigned limits
  """

  @derive [Poison.Encoder]
  defstruct [
    :factor,
    :max,
    :min
  ]

  @type t :: %__MODULE__{
    :factor => float() | nil,
    :max => SlurmRestAPI.Model.Dbv0038QosLimitsMax.t | nil,
    :min => SlurmRestAPI.Model.Dbv0038QosLimitsMin.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038QosLimits do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:max, :struct, SlurmRestAPI.Model.Dbv0038QosLimitsMax, options)
    |> deserialize(:min, :struct, SlurmRestAPI.Model.Dbv0038QosLimitsMin, options)
  end
end

