# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037User do
  @moduledoc """
  User description
  """

  @derive [Poison.Encoder]
  defstruct [
    :administrator_level,
    :associations,
    :coordinators,
    :default,
    :name
  ]

  @type t :: %__MODULE__{
    :administrator_level => String.t | nil,
    :associations => SlurmRestAPI.Model.Dbv0037UserAssociations.t | nil,
    :coordinators => [SlurmRestAPI.Model.Dbv0037CoordinatorInfo.t] | nil,
    :default => SlurmRestAPI.Model.Dbv0037UserDefault.t | nil,
    :name => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037User do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:associations, :struct, SlurmRestAPI.Model.Dbv0037UserAssociations, options)
    |> deserialize(:coordinators, :list, SlurmRestAPI.Model.Dbv0037CoordinatorInfo, options)
    |> deserialize(:default, :struct, SlurmRestAPI.Model.Dbv0037UserDefault, options)
  end
end

