# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037JobStep do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :time,
    :exit_code,
    :nodes,
    :tasks,
    :pid,
    :CPU,
    :kill_request_user,
    :state,
    :statistics,
    :step,
    :task,
    :tres
  ]

  @type t :: %__MODULE__{
    :time => SlurmRestAPI.Model.Dbv0037JobStepTime.t | nil,
    :exit_code => SlurmRestAPI.Model.Dbv0037JobExitCode.t | nil,
    :nodes => SlurmRestAPI.Model.Dbv0037JobStepNodes.t | nil,
    :tasks => SlurmRestAPI.Model.Dbv0037JobStepTasks.t | nil,
    :pid => String.t | nil,
    :CPU => SlurmRestAPI.Model.Dbv0037JobStepCpu.t | nil,
    :kill_request_user => String.t | nil,
    :state => String.t | nil,
    :statistics => SlurmRestAPI.Model.Dbv0037JobStepStatistics.t | nil,
    :step => SlurmRestAPI.Model.Dbv0037JobStepStep.t | nil,
    :task => SlurmRestAPI.Model.Dbv0037JobStepTask.t | nil,
    :tres => SlurmRestAPI.Model.Dbv0037JobStepTres.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037JobStep do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:time, :struct, SlurmRestAPI.Model.Dbv0037JobStepTime, options)
    |> deserialize(:exit_code, :struct, SlurmRestAPI.Model.Dbv0037JobExitCode, options)
    |> deserialize(:nodes, :struct, SlurmRestAPI.Model.Dbv0037JobStepNodes, options)
    |> deserialize(:tasks, :struct, SlurmRestAPI.Model.Dbv0037JobStepTasks, options)
    |> deserialize(:CPU, :struct, SlurmRestAPI.Model.Dbv0037JobStepCpu, options)
    |> deserialize(:statistics, :struct, SlurmRestAPI.Model.Dbv0037JobStepStatistics, options)
    |> deserialize(:step, :struct, SlurmRestAPI.Model.Dbv0037JobStepStep, options)
    |> deserialize(:task, :struct, SlurmRestAPI.Model.Dbv0037JobStepTask, options)
    |> deserialize(:tres, :struct, SlurmRestAPI.Model.Dbv0037JobStepTres, options)
  end
end

