# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037Account do
  @moduledoc """
  Account description
  """

  @derive [Poison.Encoder]
  defstruct [
    :associations,
    :coordinators,
    :description,
    :name,
    :organization,
    :flags
  ]

  @type t :: %__MODULE__{
    :associations => [SlurmRestAPI.Model.Dbv0037AssociationShortInfo.t] | nil,
    :coordinators => [SlurmRestAPI.Model.Dbv0037CoordinatorInfo.t] | nil,
    :description => String.t | nil,
    :name => String.t | nil,
    :organization => String.t | nil,
    :flags => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037Account do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:associations, :list, SlurmRestAPI.Model.Dbv0037AssociationShortInfo, options)
    |> deserialize(:coordinators, :list, SlurmRestAPI.Model.Dbv0037CoordinatorInfo, options)
  end
end

