# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037AssociationMax do
  @moduledoc """
  Max settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :jobs,
    :per,
    :tres
  ]

  @type t :: %__MODULE__{
    :jobs => SlurmRestAPI.Model.Dbv0037AssociationMaxJobs.t | nil,
    :per => SlurmRestAPI.Model.Dbv0037AssociationMaxPer.t | nil,
    :tres => SlurmRestAPI.Model.Dbv0037AssociationMaxTres.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037AssociationMax do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:jobs, :struct, SlurmRestAPI.Model.Dbv0037AssociationMaxJobs, options)
    |> deserialize(:per, :struct, SlurmRestAPI.Model.Dbv0037AssociationMaxPer, options)
    |> deserialize(:tres, :struct, SlurmRestAPI.Model.Dbv0037AssociationMaxTres, options)
  end
end

