# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038JobStep do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :time,
    :exit_code,
    :nodes,
    :tasks,
    :pid,
    :CPU,
    :kill_request_user,
    :state,
    :statistics,
    :step,
    :task,
    :tres
  ]

  @type t :: %__MODULE__{
    :time => SlurmRestAPI.Model.Dbv0038JobStepTime.t | nil,
    :exit_code => SlurmRestAPI.Model.Dbv0038JobExitCode.t | nil,
    :nodes => SlurmRestAPI.Model.Dbv0038JobStepNodes.t | nil,
    :tasks => SlurmRestAPI.Model.Dbv0038JobStepTasks.t | nil,
    :pid => String.t | nil,
    :CPU => SlurmRestAPI.Model.Dbv0038JobStepCpu.t | nil,
    :kill_request_user => String.t | nil,
    :state => String.t | nil,
    :statistics => SlurmRestAPI.Model.Dbv0038JobStepStatistics.t | nil,
    :step => SlurmRestAPI.Model.Dbv0038JobStepStep.t | nil,
    :task => String.t | nil,
    :tres => SlurmRestAPI.Model.Dbv0038JobStepTres.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038JobStep do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:time, :struct, SlurmRestAPI.Model.Dbv0038JobStepTime, options)
    |> deserialize(:exit_code, :struct, SlurmRestAPI.Model.Dbv0038JobExitCode, options)
    |> deserialize(:nodes, :struct, SlurmRestAPI.Model.Dbv0038JobStepNodes, options)
    |> deserialize(:tasks, :struct, SlurmRestAPI.Model.Dbv0038JobStepTasks, options)
    |> deserialize(:CPU, :struct, SlurmRestAPI.Model.Dbv0038JobStepCpu, options)
    |> deserialize(:statistics, :struct, SlurmRestAPI.Model.Dbv0038JobStepStatistics, options)
    |> deserialize(:step, :struct, SlurmRestAPI.Model.Dbv0038JobStepStep, options)
    |> deserialize(:tres, :struct, SlurmRestAPI.Model.Dbv0038JobStepTres, options)
  end
end

