# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038QosLimitsMaxWallClockPer do
  @moduledoc """
  Limit on wallclock per settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :qos,
    :job
  ]

  @type t :: %__MODULE__{
    :qos => integer() | nil,
    :job => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038QosLimitsMaxWallClockPer do
  def decode(value, _options) do
    value
  end
end

