# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037DiagStatisticsUsersInner do
  @moduledoc """
  Statistics by user RPCs
  """

  @derive [Poison.Encoder]
  defstruct [
    :user,
    :count,
    :time
  ]

  @type t :: %__MODULE__{
    :user => String.t | nil,
    :count => integer() | nil,
    :time => SlurmRestAPI.Model.Dbv0037DiagStatisticsUsersInnerTime.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037DiagStatisticsUsersInner do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:time, :struct, SlurmRestAPI.Model.Dbv0037DiagStatisticsUsersInnerTime, options)
  end
end

