# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038JobStepStepHet do
  @moduledoc """
  Heterogeneous job details
  """

  @derive [Poison.Encoder]
  defstruct [
    :component
  ]

  @type t :: %__MODULE__{
    :component => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038JobStepStepHet do
  def decode(value, _options) do
    value
  end
end

