# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038AssociationMaxTresPer do
  @moduledoc """
  Max TRES per settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :job,
    :node
  ]

  @type t :: %__MODULE__{
    :job => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil,
    :node => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038AssociationMaxTresPer do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:job, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
    |> deserialize(:node, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
  end
end

