# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037Job do
  @moduledoc """
  Single job description
  """

  @derive [Poison.Encoder]
  defstruct [
    :account,
    :comment,
    :allocation_nodes,
    :array,
    :time,
    :association,
    :cluster,
    :constraints,
    :derived_exit_code,
    :exit_code,
    :flags,
    :group,
    :het,
    :job_id,
    :name,
    :mcs,
    :nodes,
    :partition,
    :priority,
    :qos,
    :required,
    :kill_request_user,
    :reservation,
    :state,
    :steps,
    :tres,
    :user,
    :wckey,
    :working_directory
  ]

  @type t :: %__MODULE__{
    :account => String.t | nil,
    :comment => SlurmRestAPI.Model.Dbv0037JobComment.t | nil,
    :allocation_nodes => String.t | nil,
    :array => SlurmRestAPI.Model.Dbv0037JobArray.t | nil,
    :time => SlurmRestAPI.Model.Dbv0037JobTime.t | nil,
    :association => SlurmRestAPI.Model.Dbv0037AssociationShortInfo.t | nil,
    :cluster => String.t | nil,
    :constraints => String.t | nil,
    :derived_exit_code => SlurmRestAPI.Model.Dbv0037JobExitCode.t | nil,
    :exit_code => SlurmRestAPI.Model.Dbv0037JobExitCode.t | nil,
    :flags => [String.t] | nil,
    :group => String.t | nil,
    :het => SlurmRestAPI.Model.Dbv0037JobHet.t | nil,
    :job_id => integer() | nil,
    :name => String.t | nil,
    :mcs => SlurmRestAPI.Model.Dbv0037JobMcs.t | nil,
    :nodes => String.t | nil,
    :partition => String.t | nil,
    :priority => integer() | nil,
    :qos => String.t | nil,
    :required => SlurmRestAPI.Model.Dbv0037JobRequired.t | nil,
    :kill_request_user => String.t | nil,
    :reservation => SlurmRestAPI.Model.Dbv0037JobReservation.t | nil,
    :state => SlurmRestAPI.Model.Dbv0037JobState.t | nil,
    :steps => [SlurmRestAPI.Model.Dbv0037JobStep.t] | nil,
    :tres => SlurmRestAPI.Model.Dbv0037JobTres.t | nil,
    :user => String.t | nil,
    :wckey => SlurmRestAPI.Model.Dbv0037JobWckey.t | nil,
    :working_directory => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037Job do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:comment, :struct, SlurmRestAPI.Model.Dbv0037JobComment, options)
    |> deserialize(:array, :struct, SlurmRestAPI.Model.Dbv0037JobArray, options)
    |> deserialize(:time, :struct, SlurmRestAPI.Model.Dbv0037JobTime, options)
    |> deserialize(:association, :struct, SlurmRestAPI.Model.Dbv0037AssociationShortInfo, options)
    |> deserialize(:derived_exit_code, :struct, SlurmRestAPI.Model.Dbv0037JobExitCode, options)
    |> deserialize(:exit_code, :struct, SlurmRestAPI.Model.Dbv0037JobExitCode, options)
    |> deserialize(:het, :struct, SlurmRestAPI.Model.Dbv0037JobHet, options)
    |> deserialize(:mcs, :struct, SlurmRestAPI.Model.Dbv0037JobMcs, options)
    |> deserialize(:required, :struct, SlurmRestAPI.Model.Dbv0037JobRequired, options)
    |> deserialize(:reservation, :struct, SlurmRestAPI.Model.Dbv0037JobReservation, options)
    |> deserialize(:state, :struct, SlurmRestAPI.Model.Dbv0037JobState, options)
    |> deserialize(:steps, :list, SlurmRestAPI.Model.Dbv0037JobStep, options)
    |> deserialize(:tres, :struct, SlurmRestAPI.Model.Dbv0037JobTres, options)
    |> deserialize(:wckey, :struct, SlurmRestAPI.Model.Dbv0037JobWckey, options)
  end
end

