# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038AssociationMaxTres do
  @moduledoc """
  Max TRES settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :per,
    :total,
    :minutes
  ]

  @type t :: %__MODULE__{
    :per => SlurmRestAPI.Model.Dbv0038AssociationMaxTresPer.t | nil,
    :total => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil,
    :minutes => SlurmRestAPI.Model.Dbv0038AssociationMaxTresMinutes.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038AssociationMaxTres do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:per, :struct, SlurmRestAPI.Model.Dbv0038AssociationMaxTresPer, options)
    |> deserialize(:total, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
    |> deserialize(:minutes, :struct, SlurmRestAPI.Model.Dbv0038AssociationMaxTresMinutes, options)
  end
end

