# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038AssociationShortInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :account,
    :cluster,
    :partition,
    :user
  ]

  @type t :: %__MODULE__{
    :account => String.t | nil,
    :cluster => String.t | nil,
    :partition => String.t | nil,
    :user => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038AssociationShortInfo do
  def decode(value, _options) do
    value
  end
end

