# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038Accounting do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :allocated,
    :id,
    :start,
    :TRES
  ]

  @type t :: %__MODULE__{
    :allocated => integer() | nil,
    :id => integer() | nil,
    :start => integer() | nil,
    :TRES => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038Accounting do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:TRES, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
  end
end

