# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037JobRequired do
  @moduledoc """
  Job run requirements
  """

  @derive [Poison.Encoder]
  defstruct [
    :CPUs,
    :memory
  ]

  @type t :: %__MODULE__{
    :CPUs => integer() | nil,
    :memory => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037JobRequired do
  def decode(value, _options) do
    value
  end
end

