# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038UpdateQos do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :qos
  ]

  @type t :: %__MODULE__{
    :qos => [SlurmRestAPI.Model.Dbv0038Qos.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038UpdateQos do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:qos, :list, SlurmRestAPI.Model.Dbv0038Qos, options)
  end
end

