# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037JobStepTresRequested do
  @moduledoc """
  TRES requested for job
  """

  @derive [Poison.Encoder]
  defstruct [
    :average,
    :max,
    :min,
    :total
  ]

  @type t :: %__MODULE__{
    :average => [SlurmRestAPI.Model.Dbv0037TresListInner.t] | nil,
    :max => [SlurmRestAPI.Model.Dbv0037TresListInner.t] | nil,
    :min => [SlurmRestAPI.Model.Dbv0037TresListInner.t] | nil,
    :total => [SlurmRestAPI.Model.Dbv0037TresListInner.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037JobStepTresRequested do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:average, :list, SlurmRestAPI.Model.Dbv0037TresListInner, options)
    |> deserialize(:max, :list, SlurmRestAPI.Model.Dbv0037TresListInner, options)
    |> deserialize(:min, :list, SlurmRestAPI.Model.Dbv0037TresListInner, options)
    |> deserialize(:total, :list, SlurmRestAPI.Model.Dbv0037TresListInner, options)
  end
end

