# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037JobExitCode do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :status,
    :return_code,
    :signal
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil,
    :return_code => integer() | nil,
    :signal => SlurmRestAPI.Model.Dbv0037JobExitCodeSignal.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037JobExitCode do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:signal, :struct, SlurmRestAPI.Model.Dbv0037JobExitCodeSignal, options)
  end
end

