# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037JobStepCpu do
  @moduledoc """
  CPU properties
  """

  @derive [Poison.Encoder]
  defstruct [
    :requested_frequency,
    :governor
  ]

  @type t :: %__MODULE__{
    :requested_frequency => SlurmRestAPI.Model.Dbv0037JobStepCpuRequestedFrequency.t | nil,
    :governor => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037JobStepCpu do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:requested_frequency, :struct, SlurmRestAPI.Model.Dbv0037JobStepCpuRequestedFrequency, options)
  end
end

