# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038QosLimitsMin do
  @moduledoc """
  Min limit settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :priority_threshold,
    :tres
  ]

  @type t :: %__MODULE__{
    :priority_threshold => integer() | nil,
    :tres => SlurmRestAPI.Model.Dbv0038QosLimitsMinTres.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038QosLimitsMin do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tres, :struct, SlurmRestAPI.Model.Dbv0038QosLimitsMinTres, options)
  end
end

