# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038ClusterInfoAssociations do
  @moduledoc """
  Information about associations
  """

  @derive [Poison.Encoder]
  defstruct [
    :root
  ]

  @type t :: %__MODULE__{
    :root => SlurmRestAPI.Model.Dbv0038AssociationShortInfo.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038ClusterInfoAssociations do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:root, :struct, SlurmRestAPI.Model.Dbv0038AssociationShortInfo, options)
  end
end

