# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038JobStepTres do
  @moduledoc """
  TRES usage
  """

  @derive [Poison.Encoder]
  defstruct [
    :requested,
    :consumed,
    :allocated
  ]

  @type t :: %__MODULE__{
    :requested => SlurmRestAPI.Model.Dbv0038JobStepTresRequested.t | nil,
    :consumed => SlurmRestAPI.Model.Dbv0038JobStepTresRequested.t | nil,
    :allocated => [SlurmRestAPI.Model.Dbv0038TresListInner.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038JobStepTres do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:requested, :struct, SlurmRestAPI.Model.Dbv0038JobStepTresRequested, options)
    |> deserialize(:consumed, :struct, SlurmRestAPI.Model.Dbv0038JobStepTresRequested, options)
    |> deserialize(:allocated, :list, SlurmRestAPI.Model.Dbv0038TresListInner, options)
  end
end

