# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037Qos do
  @moduledoc """
  QOS description
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :flags,
    :id,
    :limits,
    :preempt,
    :priority,
    :usage_factor,
    :usage_threshold
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :flags => [String.t] | nil,
    :id => String.t | nil,
    :limits => SlurmRestAPI.Model.Dbv0037QosLimits.t | nil,
    :preempt => SlurmRestAPI.Model.Dbv0037QosPreempt.t | nil,
    :priority => integer() | nil,
    :usage_factor => float() | nil,
    :usage_threshold => float() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037Qos do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:limits, :struct, SlurmRestAPI.Model.Dbv0037QosLimits, options)
    |> deserialize(:preempt, :struct, SlurmRestAPI.Model.Dbv0037QosPreempt, options)
  end
end

