# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038ClusterInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :controller,
    :flags,
    :name,
    :nodes,
    :select_plugin,
    :associations,
    :rpc_version,
    :tres
  ]

  @type t :: %__MODULE__{
    :controller => SlurmRestAPI.Model.Dbv0038ClusterInfoController.t | nil,
    :flags => [String.t] | nil,
    :name => String.t | nil,
    :nodes => String.t | nil,
    :select_plugin => String.t | nil,
    :associations => SlurmRestAPI.Model.Dbv0038ClusterInfoAssociations.t | nil,
    :rpc_version => integer() | nil,
    :tres => [SlurmRestAPI.Model.Dbv0038ResponseTres.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038ClusterInfo do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:controller, :struct, SlurmRestAPI.Model.Dbv0038ClusterInfoController, options)
    |> deserialize(:associations, :struct, SlurmRestAPI.Model.Dbv0038ClusterInfoAssociations, options)
    |> deserialize(:tres, :list, SlurmRestAPI.Model.Dbv0038ResponseTres, options)
  end
end

