# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0039Meta do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :plugin,
    :Slurm
  ]

  @type t :: %__MODULE__{
    :plugin => SlurmRestAPI.Model.V0039MetaPlugin.t | nil,
    :Slurm => SlurmRestAPI.Model.V0039MetaSlurm.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0039Meta do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:plugin, :struct, SlurmRestAPI.Model.V0039MetaPlugin, options)
    |> deserialize(:Slurm, :struct, SlurmRestAPI.Model.V0039MetaSlurm, options)
  end
end

