# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037JobStepTask do
  @moduledoc """
  Task properties
  """

  @derive [Poison.Encoder]
  defstruct [
    :distribution
  ]

  @type t :: %__MODULE__{
    :distribution => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037JobStepTask do
  def decode(value, _options) do
    value
  end
end

