# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037ConfigInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :errors,
    :tres,
    :accounts,
    :associations,
    :users,
    :qos,
    :wckeys
  ]

  @type t :: %__MODULE__{
    :errors => [SlurmRestAPI.Model.Dbv0037Error.t] | nil,
    :tres => [SlurmRestAPI.Model.List.t] | nil,
    :accounts => [SlurmRestAPI.Model.Dbv0037Account.t] | nil,
    :associations => [SlurmRestAPI.Model.Dbv0037Association.t] | nil,
    :users => [SlurmRestAPI.Model.Dbv0037User.t] | nil,
    :qos => [SlurmRestAPI.Model.Dbv0037Qos.t] | nil,
    :wckeys => [SlurmRestAPI.Model.Dbv0037Wckey.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037ConfigInfo do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, SlurmRestAPI.Model.Dbv0037Error, options)
    |> deserialize(:accounts, :list, SlurmRestAPI.Model.Dbv0037Account, options)
    |> deserialize(:associations, :list, SlurmRestAPI.Model.Dbv0037Association, options)
    |> deserialize(:users, :list, SlurmRestAPI.Model.Dbv0037User, options)
    |> deserialize(:qos, :list, SlurmRestAPI.Model.Dbv0037Qos, options)
    |> deserialize(:wckeys, :list, SlurmRestAPI.Model.Dbv0037Wckey, options)
  end
end

