# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038QosLimitsMaxTres do
  @moduledoc """
  Limits on TRES
  """

  @derive [Poison.Encoder]
  defstruct [
    :minutes,
    :per
  ]

  @type t :: %__MODULE__{
    :minutes => SlurmRestAPI.Model.Dbv0038QosLimitsMaxTresMinutes.t | nil,
    :per => SlurmRestAPI.Model.Dbv0038QosLimitsMaxTresPer.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038QosLimitsMaxTres do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:minutes, :struct, SlurmRestAPI.Model.Dbv0038QosLimitsMaxTresMinutes, options)
    |> deserialize(:per, :struct, SlurmRestAPI.Model.Dbv0038QosLimitsMaxTresPer, options)
  end
end

