# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037AssociationMin do
  @moduledoc """
  Min settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :priority_threshold
  ]

  @type t :: %__MODULE__{
    :priority_threshold => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037AssociationMin do
  def decode(value, _options) do
    value
  end
end

