# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0039ConfigInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :meta,
    :errors,
    :warnings,
    :tres,
    :accounts,
    :associations,
    :users,
    :qos,
    :wckeys,
    :clusters
  ]

  @type t :: %__MODULE__{
    :meta => SlurmRestAPI.Model.Dbv0039Meta.t | nil,
    :errors => [SlurmRestAPI.Model.Dbv0039Error.t] | nil,
    :warnings => [SlurmRestAPI.Model.Dbv0039Warning.t] | nil,
    :tres => [SlurmRestAPI.Model.V0039Tres.t] | nil,
    :accounts => [SlurmRestAPI.Model.V0039Account.t] | nil,
    :associations => [SlurmRestAPI.Model.V0039Assoc.t] | nil,
    :users => [SlurmRestAPI.Model.V0039User.t] | nil,
    :qos => [SlurmRestAPI.Model.V0039Qos.t] | nil,
    :wckeys => [SlurmRestAPI.Model.V0039Wckey.t] | nil,
    :clusters => [SlurmRestAPI.Model.V0039ClusterRec.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0039ConfigInfo do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:meta, :struct, SlurmRestAPI.Model.Dbv0039Meta, options)
    |> deserialize(:errors, :list, SlurmRestAPI.Model.Dbv0039Error, options)
    |> deserialize(:warnings, :list, SlurmRestAPI.Model.Dbv0039Warning, options)
    |> deserialize(:tres, :list, SlurmRestAPI.Model.V0039Tres, options)
    |> deserialize(:accounts, :list, SlurmRestAPI.Model.V0039Account, options)
    |> deserialize(:associations, :list, SlurmRestAPI.Model.V0039Assoc, options)
    |> deserialize(:users, :list, SlurmRestAPI.Model.V0039User, options)
    |> deserialize(:qos, :list, SlurmRestAPI.Model.V0039Qos, options)
    |> deserialize(:wckeys, :list, SlurmRestAPI.Model.V0039Wckey, options)
    |> deserialize(:clusters, :list, SlurmRestAPI.Model.V0039ClusterRec, options)
  end
end

