# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037AssociationMaxPerAccount do
  @moduledoc """
  Max per accounting settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :wall_clock
  ]

  @type t :: %__MODULE__{
    :wall_clock => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037AssociationMaxPerAccount do
  def decode(value, _options) do
    value
  end
end

