# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038JobArrayLimits do
  @moduledoc """
  Limits on array settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :max
  ]

  @type t :: %__MODULE__{
    :max => SlurmRestAPI.Model.Dbv0038JobArrayLimitsMax.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038JobArrayLimits do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:max, :struct, SlurmRestAPI.Model.Dbv0038JobArrayLimitsMax, options)
  end
end

