# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037AssociationMaxTresGroup do
  @moduledoc """
  Max TRES per group
  """

  @derive [Poison.Encoder]
  defstruct [
    :minutes,
    :active
  ]

  @type t :: %__MODULE__{
    :minutes => [SlurmRestAPI.Model.Dbv0037TresListInner.t] | nil,
    :active => [SlurmRestAPI.Model.Dbv0037TresListInner.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037AssociationMaxTresGroup do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:minutes, :list, SlurmRestAPI.Model.Dbv0037TresListInner, options)
    |> deserialize(:active, :list, SlurmRestAPI.Model.Dbv0037TresListInner, options)
  end
end

