# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0037JobMcs do
  @moduledoc """
  Multi-Category Security
  """

  @derive [Poison.Encoder]
  defstruct [
    :label
  ]

  @type t :: %__MODULE__{
    :label => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0037JobMcs do
  def decode(value, _options) do
    value
  end
end

