# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.Dbv0038JobHet do
  @moduledoc """
  Heterogeneous Job details (optional)
  """

  @derive [Poison.Encoder]
  defstruct [
    :job_id,
    :job_offset
  ]

  @type t :: %__MODULE__{
    :job_id => integer() | nil,
    :job_offset => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.Dbv0038JobHet do
  def decode(value, _options) do
    value
  end
end

