# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039AssocMax do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :jobs
  ]

  @type t :: %__MODULE__{
    :jobs => SlurmRestAPI.Model.V0039AssocMaxJobs.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039AssocMax do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:jobs, :struct, SlurmRestAPI.Model.V0039AssocMaxJobs, options)
  end
end

