# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0037JobSubmissionResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :errors,
    :job_id,
    :step_id,
    :job_submit_user_msg
  ]

  @type t :: %__MODULE__{
    :errors => [SlurmRestAPI.Model.V0037Error.t] | nil,
    :job_id => integer() | nil,
    :step_id => String.t | nil,
    :job_submit_user_msg => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0037JobSubmissionResponse do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, SlurmRestAPI.Model.V0037Error, options)
  end
end

