# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039SlurmStepId do
  @moduledoc """
  step details
  """

  @derive [Poison.Encoder]
  defstruct [
    :job_id,
    :step_het_component,
    :step_id
  ]

  @type t :: %__MODULE__{
    :job_id => integer() | nil,
    :step_het_component => integer() | nil,
    :step_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039SlurmStepId do
  def decode(value, _options) do
    value
  end
end

