# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039PartitionInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :nodes,
    :accounts,
    :groups,
    :qos,
    :alternate,
    :tres,
    :cluster,
    :cpus,
    :defaults,
    :grace_time,
    :maximums,
    :minimums,
    :name,
    :node_sets,
    :priority,
    :timeouts,
    :suspend_time
  ]

  @type t :: %__MODULE__{
    :nodes => SlurmRestAPI.Model.V0039PartitionInfoNodes.t | nil,
    :accounts => SlurmRestAPI.Model.V0039PartitionInfoAccounts.t | nil,
    :groups => SlurmRestAPI.Model.V0039PartitionInfoGroups.t | nil,
    :qos => SlurmRestAPI.Model.V0039PartitionInfoQos.t | nil,
    :alternate => String.t | nil,
    :tres => SlurmRestAPI.Model.V0039PartitionInfoTres.t | nil,
    :cluster => String.t | nil,
    :cpus => SlurmRestAPI.Model.V0039PartitionInfoNodes.t | nil,
    :defaults => SlurmRestAPI.Model.V0039PartitionInfoDefaults.t | nil,
    :grace_time => integer() | nil,
    :maximums => SlurmRestAPI.Model.V0039PartitionInfoMaximums.t | nil,
    :minimums => SlurmRestAPI.Model.V0039PartitionInfoMinimums.t | nil,
    :name => String.t | nil,
    :node_sets => String.t | nil,
    :priority => SlurmRestAPI.Model.V0039PartitionInfoPriority.t | nil,
    :timeouts => SlurmRestAPI.Model.V0039PartitionInfoTimeouts.t | nil,
    :suspend_time => SlurmRestAPI.Model.V0039Uint32NoVal.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039PartitionInfo do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:nodes, :struct, SlurmRestAPI.Model.V0039PartitionInfoNodes, options)
    |> deserialize(:accounts, :struct, SlurmRestAPI.Model.V0039PartitionInfoAccounts, options)
    |> deserialize(:groups, :struct, SlurmRestAPI.Model.V0039PartitionInfoGroups, options)
    |> deserialize(:qos, :struct, SlurmRestAPI.Model.V0039PartitionInfoQos, options)
    |> deserialize(:tres, :struct, SlurmRestAPI.Model.V0039PartitionInfoTres, options)
    |> deserialize(:cpus, :struct, SlurmRestAPI.Model.V0039PartitionInfoNodes, options)
    |> deserialize(:defaults, :struct, SlurmRestAPI.Model.V0039PartitionInfoDefaults, options)
    |> deserialize(:maximums, :struct, SlurmRestAPI.Model.V0039PartitionInfoMaximums, options)
    |> deserialize(:minimums, :struct, SlurmRestAPI.Model.V0039PartitionInfoMinimums, options)
    |> deserialize(:priority, :struct, SlurmRestAPI.Model.V0039PartitionInfoPriority, options)
    |> deserialize(:timeouts, :struct, SlurmRestAPI.Model.V0039PartitionInfoTimeouts, options)
    |> deserialize(:suspend_time, :struct, SlurmRestAPI.Model.V0039Uint32NoVal, options)
  end
end

