# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039WckeyTag do
  @moduledoc """
  wckey details
  """

  @derive [Poison.Encoder]
  defstruct [
    :wckey,
    :flags
  ]

  @type t :: %__MODULE__{
    :wckey => String.t | nil,
    :flags => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039WckeyTag do
  def decode(value, _options) do
    value
  end
end

