# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0038NodeAllocationSockets do
  @moduledoc """
  assignment status of each socket by numeric socket id
  """

  @derive [Poison.Encoder]
  defstruct [
    :cores
  ]

  @type t :: %__MODULE__{
    :cores => map() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0038NodeAllocationSockets do
  def decode(value, _options) do
    value
  end
end

