# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039Qos do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :flags,
    :id,
    :limits,
    :name,
    :preempt,
    :priority,
    :usage_factor,
    :usage_threshold
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :flags => [String.t] | nil,
    :id => integer() | nil,
    :limits => SlurmRestAPI.Model.V0039QosLimits.t | nil,
    :name => String.t | nil,
    :preempt => SlurmRestAPI.Model.V0039QosPreempt.t | nil,
    :priority => integer() | nil,
    :usage_factor => SlurmRestAPI.Model.V0039Float64NoVal.t | nil,
    :usage_threshold => SlurmRestAPI.Model.V0039Float64NoVal.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039Qos do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:limits, :struct, SlurmRestAPI.Model.V0039QosLimits, options)
    |> deserialize(:preempt, :struct, SlurmRestAPI.Model.V0039QosPreempt, options)
    |> deserialize(:usage_factor, :struct, SlurmRestAPI.Model.V0039Float64NoVal, options)
    |> deserialize(:usage_threshold, :struct, SlurmRestAPI.Model.V0039Float64NoVal, options)
  end
end

