# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039ReservationInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts,
    :burst_buffer,
    :core_count,
    :core_specializations,
    :end_time,
    :features,
    :flags,
    :groups,
    :licenses,
    :max_start_delay,
    :name,
    :node_count,
    :node_list,
    :partition,
    :purge_completed,
    :start_time,
    :watts,
    :tres,
    :users
  ]

  @type t :: %__MODULE__{
    :accounts => String.t | nil,
    :burst_buffer => String.t | nil,
    :core_count => integer() | nil,
    :core_specializations => [SlurmRestAPI.Model.V0039ReservationCoreSpec.t] | nil,
    :end_time => integer() | nil,
    :features => String.t | nil,
    :flags => [String.t] | nil,
    :groups => String.t | nil,
    :licenses => String.t | nil,
    :max_start_delay => integer() | nil,
    :name => String.t | nil,
    :node_count => integer() | nil,
    :node_list => String.t | nil,
    :partition => String.t | nil,
    :purge_completed => SlurmRestAPI.Model.V0039ReservationInfoPurgeCompleted.t | nil,
    :start_time => integer() | nil,
    :watts => SlurmRestAPI.Model.V0039Uint32NoVal.t | nil,
    :tres => String.t | nil,
    :users => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039ReservationInfo do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:core_specializations, :list, SlurmRestAPI.Model.V0039ReservationCoreSpec, options)
    |> deserialize(:purge_completed, :struct, SlurmRestAPI.Model.V0039ReservationInfoPurgeCompleted, options)
    |> deserialize(:watts, :struct, SlurmRestAPI.Model.V0039Uint32NoVal, options)
  end
end

