# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039RollupStatsInner do
  @moduledoc """
  recorded rollup statistics
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :"last run",
    :max_cycle,
    :total_time,
    :total_cycles,
    :mean_cycles
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :"last run" => integer() | nil,
    :max_cycle => integer() | nil,
    :total_time => integer() | nil,
    :total_cycles => integer() | nil,
    :mean_cycles => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039RollupStatsInner do
  def decode(value, _options) do
    value
  end
end

