# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039License do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :LicenseName,
    :Total,
    :Used,
    :Free,
    :Remote,
    :Reserved,
    :LastConsumed,
    :LastDeficit,
    :LastUpdate
  ]

  @type t :: %__MODULE__{
    :LicenseName => String.t | nil,
    :Total => integer() | nil,
    :Used => integer() | nil,
    :Free => integer() | nil,
    :Remote => boolean() | nil,
    :Reserved => integer() | nil,
    :LastConsumed => integer() | nil,
    :LastDeficit => integer() | nil,
    :LastUpdate => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039License do
  def decode(value, _options) do
    value
  end
end

