# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039User do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :administrator_level,
    :associations,
    :coordinators,
    :default,
    :flags,
    :name,
    :old_name,
    :wckeys
  ]

  @type t :: %__MODULE__{
    :administrator_level => [String.t] | nil,
    :associations => [SlurmRestAPI.Model.V0039AssocShort.t] | nil,
    :coordinators => [SlurmRestAPI.Model.V0039Coord.t] | nil,
    :default => SlurmRestAPI.Model.V0039UserDefault.t | nil,
    :flags => [String.t] | nil,
    :name => String.t,
    :old_name => String.t | nil,
    :wckeys => [SlurmRestAPI.Model.V0039Wckey.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039User do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:associations, :list, SlurmRestAPI.Model.V0039AssocShort, options)
    |> deserialize(:coordinators, :list, SlurmRestAPI.Model.V0039Coord, options)
    |> deserialize(:default, :struct, SlurmRestAPI.Model.V0039UserDefault, options)
    |> deserialize(:wckeys, :list, SlurmRestAPI.Model.V0039Wckey, options)
  end
end

