# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0037ReservationsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :errors,
    :reservations
  ]

  @type t :: %__MODULE__{
    :errors => [SlurmRestAPI.Model.V0037Error.t] | nil,
    :reservations => [SlurmRestAPI.Model.V0037Reservation.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0037ReservationsResponse do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, SlurmRestAPI.Model.V0037Error, options)
    |> deserialize(:reservations, :list, SlurmRestAPI.Model.V0037Reservation, options)
  end
end

