# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0038Licenses do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :errors,
    :licenses
  ]

  @type t :: %__MODULE__{
    :errors => [SlurmRestAPI.Model.V0038Error.t] | nil,
    :licenses => [SlurmRestAPI.Model.V0038License.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0038Licenses do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, SlurmRestAPI.Model.V0038Error, options)
    |> deserialize(:licenses, :list, SlurmRestAPI.Model.V0038License, options)
  end
end

