# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039Wckey do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounting,
    :cluster,
    :id,
    :name,
    :user,
    :flags
  ]

  @type t :: %__MODULE__{
    :accounting => [SlurmRestAPI.Model.V0039Accounting.t] | nil,
    :cluster => String.t,
    :id => integer() | nil,
    :name => String.t,
    :user => String.t,
    :flags => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039Wckey do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:accounting, :list, SlurmRestAPI.Model.V0039Accounting, options)
  end
end

