# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039JobSubmission do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :script,
    :job,
    :jobs
  ]

  @type t :: %__MODULE__{
    :script => String.t | nil,
    :job => SlurmRestAPI.Model.V0039JobDescMsg.t | nil,
    :jobs => [SlurmRestAPI.Model.V0039JobDescMsg.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039JobSubmission do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:job, :struct, SlurmRestAPI.Model.V0039JobDescMsg, options)
    |> deserialize(:jobs, :list, SlurmRestAPI.Model.V0039JobDescMsg, options)
  end
end

