# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0037Reservation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts,
    :burst_buffer,
    :core_count,
    :core_spec_cnt,
    :end_time,
    :features,
    :flags,
    :groups,
    :licenses,
    :max_start_delay,
    :name,
    :node_count,
    :node_list,
    :partition,
    :purge_completed,
    :start_time,
    :watts,
    :tres,
    :users
  ]

  @type t :: %__MODULE__{
    :accounts => String.t | nil,
    :burst_buffer => String.t | nil,
    :core_count => integer() | nil,
    :core_spec_cnt => integer() | nil,
    :end_time => integer() | nil,
    :features => String.t | nil,
    :flags => [String.t] | nil,
    :groups => String.t | nil,
    :licenses => String.t | nil,
    :max_start_delay => integer() | nil,
    :name => String.t | nil,
    :node_count => integer() | nil,
    :node_list => String.t | nil,
    :partition => String.t | nil,
    :purge_completed => SlurmRestAPI.Model.V0037ReservationPurgeCompleted.t | nil,
    :start_time => integer() | nil,
    :watts => integer() | nil,
    :tres => String.t | nil,
    :users => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0037Reservation do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:purge_completed, :struct, SlurmRestAPI.Model.V0037ReservationPurgeCompleted, options)
  end
end

