# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039UpdateNodeMsg do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :comment,
    :cpu_bind,
    :extra,
    :features,
    :features_act,
    :gres,
    :address,
    :hostname,
    :name,
    :state,
    :reason,
    :reason_uid,
    :resume_after,
    :weight
  ]

  @type t :: %__MODULE__{
    :comment => String.t | nil,
    :cpu_bind => integer() | nil,
    :extra => String.t | nil,
    :features => [String.t] | nil,
    :features_act => [String.t] | nil,
    :gres => String.t | nil,
    :address => [String.t] | nil,
    :hostname => [String.t] | nil,
    :name => [String.t] | nil,
    :state => [String.t] | nil,
    :reason => String.t | nil,
    :reason_uid => String.t | nil,
    :resume_after => SlurmRestAPI.Model.V0039Uint32NoVal.t | nil,
    :weight => SlurmRestAPI.Model.V0039Uint32NoVal.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039UpdateNodeMsg do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:resume_after, :struct, SlurmRestAPI.Model.V0039Uint32NoVal, options)
    |> deserialize(:weight, :struct, SlurmRestAPI.Model.V0039Uint32NoVal, options)
  end
end

