# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039ClusterRecAssociations do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :root
  ]

  @type t :: %__MODULE__{
    :root => SlurmRestAPI.Model.V0039AssocShort.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039ClusterRecAssociations do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:root, :struct, SlurmRestAPI.Model.V0039AssocShort, options)
  end
end

