# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0038NodeAllocation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :memory,
    :cpus,
    :sockets,
    :nodename
  ]

  @type t :: %__MODULE__{
    :memory => integer() | nil,
    :cpus => integer() | nil,
    :sockets => SlurmRestAPI.Model.V0038NodeAllocationSockets.t | nil,
    :nodename => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0038NodeAllocation do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sockets, :struct, SlurmRestAPI.Model.V0038NodeAllocationSockets, options)
  end
end

