# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039MetaSlurmVersion do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :major,
    :micro,
    :minor
  ]

  @type t :: %__MODULE__{
    :major => integer() | nil,
    :micro => integer() | nil,
    :minor => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039MetaSlurmVersion do
  def decode(value, _options) do
    value
  end
end

