# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039PartitionsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :meta,
    :errors,
    :warnings,
    :partitions
  ]

  @type t :: %__MODULE__{
    :meta => SlurmRestAPI.Model.V0039Meta.t | nil,
    :errors => [SlurmRestAPI.Model.V0039Error.t] | nil,
    :warnings => [SlurmRestAPI.Model.V0039Warning.t] | nil,
    :partitions => [SlurmRestAPI.Model.V0039PartitionInfo.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039PartitionsResponse do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:meta, :struct, SlurmRestAPI.Model.V0039Meta, options)
    |> deserialize(:errors, :list, SlurmRestAPI.Model.V0039Error, options)
    |> deserialize(:warnings, :list, SlurmRestAPI.Model.V0039Warning, options)
    |> deserialize(:partitions, :list, SlurmRestAPI.Model.V0039PartitionInfo, options)
  end
end

