# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039JobRes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :nodes,
    :allocated_cores,
    :allocated_cpus,
    :allocated_hosts,
    :allocated_nodes
  ]

  @type t :: %__MODULE__{
    :nodes => String.t | nil,
    :allocated_cores => integer() | nil,
    :allocated_cpus => integer() | nil,
    :allocated_hosts => integer() | nil,
    :allocated_nodes => [any()] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039JobRes do
  def decode(value, _options) do
    value
  end
end

