# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0038DiagRpcu do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :user,
    :user_id,
    :count,
    :average_time,
    :total_time
  ]

  @type t :: %__MODULE__{
    :user => String.t | nil,
    :user_id => integer() | nil,
    :count => integer() | nil,
    :average_time => integer() | nil,
    :total_time => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0038DiagRpcu do
  def decode(value, _options) do
    value
  end
end

