# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0038Node do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :architecture,
    :burstbuffer_network_address,
    :boards,
    :boot_time,
    :cores,
    :cpu_binding,
    :cpu_load,
    :free_memory,
    :cpus,
    :features,
    :active_features,
    :gres,
    :gres_drained,
    :gres_used,
    :mcs_label,
    :name,
    :next_state_after_reboot,
    :next_state_after_reboot_flags,
    :address,
    :hostname,
    :state,
    :state_flags,
    :operating_system,
    :owner,
    :partitions,
    :port,
    :real_memory,
    :reason,
    :reason_changed_at,
    :reason_set_by_user,
    :slurmd_start_time,
    :sockets,
    :threads,
    :temporary_disk,
    :weight,
    :tres,
    :tres_used,
    :tres_weighted,
    :slurmd_version,
    :alloc_cpus,
    :idle_cpus,
    :alloc_memory
  ]

  @type t :: %__MODULE__{
    :architecture => String.t | nil,
    :burstbuffer_network_address => String.t | nil,
    :boards => integer() | nil,
    :boot_time => integer() | nil,
    :cores => integer() | nil,
    :cpu_binding => integer() | nil,
    :cpu_load => integer() | nil,
    :free_memory => integer() | nil,
    :cpus => integer() | nil,
    :features => String.t | nil,
    :active_features => String.t | nil,
    :gres => String.t | nil,
    :gres_drained => String.t | nil,
    :gres_used => String.t | nil,
    :mcs_label => String.t | nil,
    :name => String.t | nil,
    :next_state_after_reboot => String.t | nil,
    :next_state_after_reboot_flags => [String.t] | nil,
    :address => String.t | nil,
    :hostname => String.t | nil,
    :state => String.t | nil,
    :state_flags => [String.t] | nil,
    :operating_system => String.t | nil,
    :owner => String.t | nil,
    :partitions => [String.t] | nil,
    :port => integer() | nil,
    :real_memory => integer() | nil,
    :reason => String.t | nil,
    :reason_changed_at => integer() | nil,
    :reason_set_by_user => String.t | nil,
    :slurmd_start_time => integer() | nil,
    :sockets => integer() | nil,
    :threads => integer() | nil,
    :temporary_disk => integer() | nil,
    :weight => integer() | nil,
    :tres => String.t | nil,
    :tres_used => String.t | nil,
    :tres_weighted => float() | nil,
    :slurmd_version => String.t | nil,
    :alloc_cpus => integer() | nil,
    :idle_cpus => integer() | nil,
    :alloc_memory => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0038Node do
  def decode(value, _options) do
    value
  end
end

