# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0037Error do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :error,
    :errno
  ]

  @type t :: %__MODULE__{
    :error => String.t | nil,
    :errno => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0037Error do
  def decode(value, _options) do
    value
  end
end

