# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039JobTres do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :requested
  ]

  @type t :: %__MODULE__{
    :requested => [SlurmRestAPI.Model.V0039Tres.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039JobTres do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:requested, :list, SlurmRestAPI.Model.V0039Tres, options)
  end
end

