# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0038Error do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :error,
    :error_number
  ]

  @type t :: %__MODULE__{
    :error => String.t | nil,
    :error_number => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0038Error do
  def decode(value, _options) do
    value
  end
end

