# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0037PartitionsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :errors,
    :partitions
  ]

  @type t :: %__MODULE__{
    :errors => [SlurmRestAPI.Model.V0037Error.t] | nil,
    :partitions => [SlurmRestAPI.Model.V0037Partition.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0037PartitionsResponse do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errors, :list, SlurmRestAPI.Model.V0037Error, options)
    |> deserialize(:partitions, :list, SlurmRestAPI.Model.V0037Partition, options)
  end
end

