# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039ReservationCoreSpec do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :node,
    :core
  ]

  @type t :: %__MODULE__{
    :node => String.t | nil,
    :core => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039ReservationCoreSpec do
  def decode(value, _options) do
    value
  end
end

