# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039AccountingAllocated do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :seconds
  ]

  @type t :: %__MODULE__{
    :seconds => integer() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039AccountingAllocated do
  def decode(value, _options) do
    value
  end
end

