# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0037NodeAllocation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :memory,
    :cpus,
    :sockets,
    :cores
  ]

  @type t :: %__MODULE__{
    :memory => integer() | nil,
    :cpus => map() | nil,
    :sockets => map() | nil,
    :cores => map() | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0037NodeAllocation do
  def decode(value, _options) do
    value
  end
end

