# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039ControllerPing do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :hostname,
    :pinged,
    :latency,
    :mode
  ]

  @type t :: %__MODULE__{
    :hostname => String.t | nil,
    :pinged => String.t | nil,
    :latency => integer() | nil,
    :mode => String.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039ControllerPing do
  def decode(value, _options) do
    value
  end
end

