# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039StatsRec do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :time_start,
    :rollups,
    :RPCs,
    :users
  ]

  @type t :: %__MODULE__{
    :time_start => integer() | nil,
    :rollups => [SlurmRestAPI.Model.V0039RollupStatsInner.t] | nil,
    :RPCs => [SlurmRestAPI.Model.V0039StatsRpc.t] | nil,
    :users => [SlurmRestAPI.Model.V0039StatsUser.t] | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039StatsRec do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:rollups, :list, SlurmRestAPI.Model.V0039RollupStatsInner, options)
    |> deserialize(:RPCs, :list, SlurmRestAPI.Model.V0039StatsRpc, options)
    |> deserialize(:users, :list, SlurmRestAPI.Model.V0039StatsUser, options)
  end
end

