# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039Step do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :time,
    :exit_code,
    :nodes,
    :tasks,
    :pid,
    :CPU,
    :kill_request_user,
    :state,
    :statistics,
    :step,
    :task,
    :tres
  ]

  @type t :: %__MODULE__{
    :time => SlurmRestAPI.Model.V0039StepTime.t | nil,
    :exit_code => SlurmRestAPI.Model.V0039JobExitCode.t | nil,
    :nodes => SlurmRestAPI.Model.V0039StepNodes.t | nil,
    :tasks => SlurmRestAPI.Model.V0039StepTasks.t | nil,
    :pid => String.t | nil,
    :CPU => SlurmRestAPI.Model.V0039StepCpu.t | nil,
    :kill_request_user => String.t | nil,
    :state => String.t | nil,
    :statistics => SlurmRestAPI.Model.V0039StepStatistics.t | nil,
    :step => SlurmRestAPI.Model.V0039JobReservation.t | nil,
    :task => SlurmRestAPI.Model.V0039StepTask.t | nil,
    :tres => SlurmRestAPI.Model.V0039StepTres.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039Step do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:time, :struct, SlurmRestAPI.Model.V0039StepTime, options)
    |> deserialize(:exit_code, :struct, SlurmRestAPI.Model.V0039JobExitCode, options)
    |> deserialize(:nodes, :struct, SlurmRestAPI.Model.V0039StepNodes, options)
    |> deserialize(:tasks, :struct, SlurmRestAPI.Model.V0039StepTasks, options)
    |> deserialize(:CPU, :struct, SlurmRestAPI.Model.V0039StepCpu, options)
    |> deserialize(:statistics, :struct, SlurmRestAPI.Model.V0039StepStatistics, options)
    |> deserialize(:step, :struct, SlurmRestAPI.Model.V0039JobReservation, options)
    |> deserialize(:task, :struct, SlurmRestAPI.Model.V0039StepTask, options)
    |> deserialize(:tres, :struct, SlurmRestAPI.Model.V0039StepTres, options)
  end
end

