# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039AssocMaxJobsPer do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :wall_clock
  ]

  @type t :: %__MODULE__{
    :wall_clock => SlurmRestAPI.Model.V0039Uint32NoVal.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039AssocMaxJobsPer do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:wall_clock, :struct, SlurmRestAPI.Model.V0039Uint32NoVal, options)
  end
end

