# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039JobHet do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :job_offset
  ]

  @type t :: %__MODULE__{
    :job_offset => SlurmRestAPI.Model.V0039Uint32NoVal.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039JobHet do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:job_offset, :struct, SlurmRestAPI.Model.V0039Uint32NoVal, options)
  end
end

