# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SlurmRestAPI.Model.V0039PartitionInfoMaximums do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :over_time_limit
  ]

  @type t :: %__MODULE__{
    :over_time_limit => SlurmRestAPI.Model.V0039Uint16NoVal.t | nil
  }
end

defimpl Poison.Decoder, for: SlurmRestAPI.Model.V0039PartitionInfoMaximums do
  import SlurmRestAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:over_time_limit, :struct, SlurmRestAPI.Model.V0039Uint16NoVal, options)
  end
end

